/**
 * SBAR Export Router
 * 
 * Server-side procedures for exporting SBAR handover summaries
 * Supports PDF generation and secure file storage
 */

import { router, protectedProcedure } from '../_core/trpc';
import { z } from 'zod';

// Input validation schema for SBAR export
const SBARExportInputSchema = z.object({
  sessionId: z.string(),
  format: z.enum(['text', 'pdf', 'html']),
  patientName: z.string(),
  emergencyType: z.string(),
  sbarContent: z.object({
    situation: z.string(),
    background: z.string(),
    assessment: z.string(),
    recommendation: z.string(),
    generatedAt: z.string(),
    generatedBy: z.string(),
  }),
});

export const sbarExportRouter = router({
  /**
   * Generate and store SBAR export
   */
  generateExport: protectedProcedure
    .input(SBARExportInputSchema)
    .mutation(async ({ input, ctx }) => {
      try {
        const { sessionId, format, patientName, emergencyType, sbarContent } = input;

        // Format content based on export type
        let exportContent: string;
        let mimeType: string;
        let fileExtension: string;

        switch (format) {
          case 'text':
            exportContent = formatAsText(sbarContent);
            mimeType = 'text/plain';
            fileExtension = 'txt';
            break;

          case 'html':
            exportContent = formatAsHTML(sbarContent);
            mimeType = 'text/html';
            fileExtension = 'html';
            break;

          case 'pdf':
            // In production, use a library like pdfkit or puppeteer
            exportContent = formatAsText(sbarContent);
            mimeType = 'application/pdf';
            fileExtension = 'pdf';
            break;

          default:
            throw new Error(`Unsupported export format: ${format}`);
        }

        // Generate filename
        const timestamp = new Date().toISOString().split('T')[0];
        const filename = `SBAR_${patientName.replace(/\s+/g, '_')}_${timestamp}.${fileExtension}`;

        // In production, store file in S3 or similar
        // For now, return the content for client-side download
        return {
          success: true,
          filename,
          content: exportContent,
          mimeType,
          sessionId,
          exportedAt: new Date().toISOString(),
        };
      } catch (error) {
        console.error('Error generating SBAR export:', error);
        throw new Error('Failed to generate SBAR export');
      }
    }),

  /**
   * Retrieve previously generated export
   */
  getExport: protectedProcedure
    .input(z.object({
      sessionId: z.string(),
      exportId: z.string(),
    }))
    .query(async ({ input, ctx }) => {
      try {
        // In production, retrieve from database or S3
        return {
          success: true,
          message: 'Export retrieved successfully',
          sessionId: input.sessionId,
          exportId: input.exportId,
        };
      } catch (error) {
        console.error('Error retrieving export:', error);
        throw new Error('Failed to retrieve export');
      }
    }),

  /**
   * List all exports for a session
   */
  listExports: protectedProcedure
    .input(z.object({
      sessionId: z.string(),
    }))
    .query(async ({ input, ctx }) => {
      try {
        // In production, query database for all exports for this session
        return {
          success: true,
          sessionId: input.sessionId,
          exports: [],
        };
      } catch (error) {
        console.error('Error listing exports:', error);
        throw new Error('Failed to list exports');
      }
    }),

  /**
   * Delete an export
   */
  deleteExport: protectedProcedure
    .input(z.object({
      sessionId: z.string(),
      exportId: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      try {
        // In production, delete from database and S3
        return {
          success: true,
          message: 'Export deleted successfully',
          sessionId: input.sessionId,
          exportId: input.exportId,
        };
      } catch (error) {
        console.error('Error deleting export:', error);
        throw new Error('Failed to delete export');
      }
    }),
});

/**
 * Format SBAR as plain text
 */
function formatAsText(sbarContent: any): string {
  return `
================================================================================
SBAR CLINICAL HANDOVER SUMMARY
================================================================================
Generated: ${sbarContent.generatedAt}
Generated by: ${sbarContent.generatedBy}
================================================================================

SITUATION
--------
${sbarContent.situation}

BACKGROUND
----------
${sbarContent.background}

ASSESSMENT
----------
${sbarContent.assessment}

RECOMMENDATION
---------------
${sbarContent.recommendation}

================================================================================
End of Report
================================================================================
`;
}

/**
 * Format SBAR as HTML
 */
function formatAsHTML(sbarContent: any): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SBAR Clinical Handover Summary</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
      line-height: 1.6;
      color: #333;
    }
    .sbar-report {
      max-width: 900px;
      margin: 0 auto;
    }
    h1 {
      text-align: center;
      border-bottom: 2px solid #333;
      padding-bottom: 10px;
      color: #000;
    }
    .metadata {
      text-align: center;
      color: #666;
      font-size: 0.9em;
      margin-bottom: 20px;
    }
    .sbar-section {
      margin-bottom: 30px;
      page-break-inside: avoid;
    }
    .sbar-section h2 {
      background-color: #f0f0f0;
      padding: 10px;
      border-left: 4px solid #0066cc;
      margin-bottom: 10px;
    }
    .sbar-section p, .sbar-section pre {
      margin: 10px 0;
      padding: 10px;
    }
    pre {
      background-color: #f9f9f9;
      padding: 10px;
      border-radius: 4px;
      overflow-x: auto;
      border: 1px solid #ddd;
    }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 0.9em;
      color: #666;
    }
    @media print {
      body { margin: 0; }
      .sbar-section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="sbar-report">
    <h1>SBAR Clinical Handover Summary</h1>
    <p class="metadata">
      Generated: ${sbarContent.generatedAt} | By: ${sbarContent.generatedBy}
    </p>
    
    <div class="sbar-section">
      <h2>SITUATION</h2>
      <p>${sbarContent.situation}</p>
    </div>
    
    <div class="sbar-section">
      <h2>BACKGROUND</h2>
      <p>${sbarContent.background}</p>
    </div>
    
    <div class="sbar-section">
      <h2>ASSESSMENT</h2>
      <pre>${sbarContent.assessment}</pre>
    </div>
    
    <div class="sbar-section">
      <h2>RECOMMENDATION</h2>
      <pre>${sbarContent.recommendation}</pre>
    </div>
    
    <div class="footer">
      <p>This SBAR summary is automatically generated from the clinical decision support system's audit trail.</p>
      <p>Review for accuracy before sharing with receiving facility.</p>
    </div>
  </div>
</body>
</html>
`;
}
