import type { Pathway } from '../stateMachine';

export const allergicPathway: Pathway = {
  id: 'allergic',
  name: 'Severe Allergic Reaction / Anaphylaxis',
  icon: '⚠️',
  description: 'Rash, swelling, difficulty breathing after exposure',
  clarifyingQuestions: [],
  // No clarifying questions needed - anaphylaxis treatment is the same regardless
  // Epinephrine first, always. Don't waste time asking questions.
  subPathways: [],
  defaultSteps: [
    {
      id: 'ana_epi',
      action: 'EPINEPHRINE (ADRENALINE) IM — NOW',
      dose: {
        drug: 'Epinephrine (Adrenaline) 1:1000',
        dosePerKg: 0.01,
        unit: 'mg',
        maxDose: 0.5,
        route: 'IM (anterolateral thigh)',
        preparation: '<6 months: 0.05 mL. 6mo-6yr: 0.15 mL (EpiPen Jr). 6-12yr: 0.3 mL. >12yr: 0.5 mL. Use 1:1000 (1 mg/mL) concentration.',
        frequency: 'Repeat every 5 minutes if no improvement (max 3 doses)',
      },
      detail: 'GIVE IMMEDIATELY. Do NOT delay for IV access. IM into anterolateral thigh. This is the ONLY life-saving treatment.',
      critical: true,
    },
    {
      id: 'ana_position',
      action: 'POSITION THE PATIENT',
      detail: 'If breathing difficulty: sit upright. If hypotensive/faint: lie flat with legs elevated. If vomiting: recovery position. Do NOT stand the patient up.',
      critical: true,
    },
    {
      id: 'ana_o2',
      action: 'HIGH-FLOW OXYGEN',
      detail: 'Non-rebreather mask at 15 L/min.',
      critical: true,
    },
    {
      id: 'ana_access',
      action: 'IV ACCESS',
      detail: 'Large bore IV. Prepare for fluid resuscitation.',
      critical: true,
    },
    {
      id: 'ana_fluids',
      action: 'FLUID BOLUS IF HYPOTENSIVE',
      dose: {
        drug: 'Normal Saline 0.9%',
        dosePerKg: 20,
        unit: 'mL',
        route: 'IV rapid push',
        preparation: 'Push rapidly. Can repeat up to 60 mL/kg.',
        frequency: 'Repeat as needed for hypotension',
      },
      detail: 'Anaphylaxis causes massive vasodilation and capillary leak. May need large volumes.',
      timer: 300,
      reassess: 'Is blood pressure improving?',
    },
    {
      id: 'ana_epi_repeat',
      action: 'REPEAT EPINEPHRINE IF NO IMPROVEMENT',
      dose: {
        drug: 'Epinephrine (Adrenaline) 1:1000',
        dosePerKg: 0.01,
        unit: 'mg',
        maxDose: 0.5,
        route: 'IM',
        frequency: 'Every 5 minutes, max 3 doses IM total',
      },
      timer: 300,
      reassess: 'Is the patient improving?',
      escalateIf: 'No improvement after 3 IM doses → start IV epinephrine infusion',
      critical: true,
    },
    {
      id: 'ana_nebulized',
      action: 'NEBULIZED SALBUTAMOL IF WHEEZING',
      dose: {
        drug: 'Salbutamol',
        dosePerKg: 0,
        unit: 'mg',
        route: 'Nebulizer',
        preparation: '<20kg: 2.5mg. ≥20kg: 5mg.',
        frequency: 'Every 20 minutes as needed',
      },
      detail: 'For persistent bronchospasm despite epinephrine.',
    },
    {
      id: 'ana_steroids',
      action: 'GIVE STEROIDS (prevents biphasic reaction)',
      dose: {
        drug: 'Hydrocortisone',
        dosePerKg: 4,
        unit: 'mg',
        maxDose: 200,
        route: 'IV',
        preparation: '<6yr: 50mg. 6-12yr: 100mg. >12yr: 200mg.',
        frequency: 'Every 6 hours for 24-48 hours',
      },
      detail: 'Does NOT treat acute anaphylaxis. Prevents biphasic reaction (recurrence 4-12 hours later).',
    },
    {
      id: 'ana_antihistamine',
      action: 'GIVE ANTIHISTAMINE',
      dose: {
        drug: 'Chlorphenamine',
        dosePerKg: 0,
        unit: 'mg',
        route: 'IV/IM',
        preparation: '<6yr: 2.5mg. 6-12yr: 5mg. >12yr: 10mg.',
      },
      detail: 'Adjunct only. Does NOT replace epinephrine. Helps with urticaria/itch.',
    },
    {
      id: 'ana_observe',
      action: 'OBSERVE FOR MINIMUM 6 HOURS',
      detail: 'Biphasic reaction can occur 4-12 hours after initial reaction. Observe minimum 6 hours (12 hours if severe). Discharge with EpiPen prescription and anaphylaxis action plan.',
      timer: 21600,
      critical: true,
    },
  ],
};
