import type { Pathway } from '../stateMachine';

export const allergicPathway: Pathway = {
  id: 'allergic',
  name: 'Severe Allergic Reaction / Anaphylaxis',
  icon: '⚠️',
  description: 'Rash, swelling, difficulty breathing after exposure',
  clarifyingQuestions: [],
  // No clarifying questions needed - anaphylaxis treatment is the same regardless
  // Epinephrine first, always. Don't waste time asking questions.
  subPathways: [],
  defaultSteps: [
    {
      id: 'ana_epi',
      action: 'EPINEPHRINE (ADRENALINE) IM — NOW',
      dose: {
        drug: 'Epinephrine (Adrenaline) 1:1000',
        dosePerKg: 0.01,
        unit: 'mg',
        maxDose: 0.5,
        route: 'IM (anterolateral thigh)',
        preparation: 'Use 0.01 mg/kg of 1:1000 (1 mg/mL) IM in the anterolateral thigh, with the approved age/weight maximum and device/formulation check. Do not delay for IV access.',
        frequency: 'Repeat every 5 minutes if no improvement (max 3 doses)',
      },
      detail: 'GIVE IMMEDIATELY. Do NOT delay for IV access. IM into anterolateral thigh. This is the ONLY life-saving treatment.',
      critical: true,
    },
    {
      id: 'ana_position',
      action: 'POSITION THE PATIENT',
      detail: 'If breathing difficulty: sit upright. If hypotensive/faint: lie flat with legs elevated. If vomiting: recovery position. Do NOT stand the patient up.',
      critical: true,
    },
    {
      id: 'ana_o2',
      action: 'AGE-APPROPRIATE OXYGEN SUPPORT IF HYPOXAEMIC',
      detail: 'Use an age-, size-, and severity-appropriate oxygen interface and titrate to the selected target. Escalate ventilation support if effort is failing.',
      critical: true,
    },
    {
      id: 'ana_access',
      action: 'IV ACCESS',
      detail: 'Large bore IV. Prepare for fluid resuscitation.',
      critical: true,
    },
    {
      id: 'ana_fluids',
      action: 'FLUID BOLUS IF HYPOTENSIVE',
      dose: {
        drug: 'Isotonic crystalloid',
        dosePerKg: 0,
        doseModel: 'protocol_only',
        unit: 'mL',
        route: 'IV/IO per shock protocol',
        preparation: 'If shock is present, use the age- and local-protocol-appropriate controlled aliquot, reassess perfusion and respiratory status after each bolus, and stop/escalate if overload or refractory shock develops.',
        frequency: 'Repeat only after reassessment and senior review',
      },
      detail: 'Anaphylaxis can cause distributive shock and capillary leak; treat hypotension with controlled fluid and early expert escalation.',
      timer: 300,
      reassess: 'Is blood pressure improving?',
    },
    {
      id: 'ana_epi_repeat',
      action: 'REPEAT EPINEPHRINE IF NO IMPROVEMENT',
      dose: {
        drug: 'Epinephrine (Adrenaline) 1:1000',
        dosePerKg: 0.01,
        unit: 'mg',
        maxDose: 0.5,
        route: 'IM',
        frequency: 'Every 5 minutes, max 3 doses IM total',
      },
      timer: 300,
      reassess: 'Is the patient improving?',
      escalateIf: 'No improvement after 3 IM doses → start IV epinephrine infusion',
      critical: true,
    },
    {
      id: 'ana_nebulized',
      action: 'NEBULIZED SALBUTAMOL IF WHEEZING',
      dose: {
        drug: 'Salbutamol',
        dosePerKg: 0,
        unit: 'mg',
        route: 'Nebulizer',
        preparation: '<20kg: 2.5mg. ≥20kg: 5mg.',
        frequency: 'Every 20 minutes as needed',
      },
      detail: 'For persistent bronchospasm despite epinephrine.',
    },
    {
      id: 'ana_steroids',
      action: 'CORTICOSTEROID — NOT ROUTINE ANAPHYLAXIS TREATMENT',
      dose: {
        drug: 'Corticosteroid',
        dosePerKg: 0,
        doseModel: 'protocol_only',
        unit: 'mg',
        maxDose: 0,
        route: 'Only for a separate governed indication',
        preparation: 'Do not use corticosteroids routinely to prevent biphasic anaphylaxis. Consult the relevant age- and diagnosis-specific protocol if another indication exists.',
      },
      detail: 'This is not acute first-line treatment and must not delay epinephrine, airway support, fluids, or expert escalation.',
    },
    {
      id: 'ana_antihistamine',
      action: 'OPTIONAL ANTIHISTAMINE AFTER STABILISATION',
      dose: {
        drug: 'Antihistamine',
        dosePerKg: 0,
        doseModel: 'protocol_only',
        unit: 'mg',
        route: 'PO/IV/IM only if approved by local protocol',
        preparation: 'Consider only for persistent skin symptoms after life-threatening airway, breathing, and circulation problems are treated; verify age, route, sedation risk, and local formulary.',
      },
      detail: 'Adjunct only. Does not treat airway compromise, shock, or the acute life-threatening process and never replaces epinephrine.',
    },
    {
      id: 'ana_observe',
      action: 'RISK-STRATIFIED OBSERVATION AND DISPOSITION',
      detail: 'Observe according to severity, number/timing of epinephrine doses, response, comorbidity, access to care, and local policy. Reassess for recurrence and provide an action plan and follow-up before discharge.',
      critical: true,
    },
  ],
};
