import type { Pathway } from '../stateMachine';

export const breathingPathway: Pathway = {
  id: 'breathing',
  name: 'Breathing Difficulty',
  icon: '🫁',
  description: 'Breathing hard, noisy breathing, low oxygen',
  clarifyingQuestions: [
    {
      id: 'wheezing',
      text: 'Is there wheezing (whistling sound breathing OUT)?',
      options: [
        { label: 'YES - Wheezing', value: 'yes' },
        { label: 'NO', value: 'no' },
      ],
    },
    {
      id: 'stridor',
      text: 'Is there stridor (harsh sound breathing IN)?',
      options: [
        { label: 'YES - Stridor', value: 'yes' },
        { label: 'NO', value: 'no' },
      ],
    },
  ],
  subPathways: [
    {
      id: 'bronchospasm',
      name: 'Bronchospasm / Asthma',
      matchCondition: (answers) => answers.wheezing === 'yes',
      steps: [
        {
          id: 'br_o2',
          action: 'HIGH-FLOW OXYGEN',
          detail: 'Non-rebreather mask at 15 L/min. Target SpO2 ≥ 94%.',
          critical: true,
        },
        {
          id: 'br_salbutamol',
          action: 'SALBUTAMOL NEBULIZER',
          dose: {
            drug: 'Salbutamol',
            dosePerKg: 0.15,
            unit: 'mg',
            maxDose: 5,
            route: 'Nebulizer',
            concentration: '5 mg/mL solution',
            preparation: '<20kg: 2.5mg (0.5mL). ≥20kg: 5mg (1mL). Dilute to 3mL with normal saline.',
            frequency: 'Can repeat every 20 minutes x3, then hourly',
          },
          timer: 1200, // 20 min
          reassess: 'Is the patient improving after salbutamol?',
          escalateIf: 'Still wheezing, still in distress, SpO2 not improving',
          critical: true,
        },
        {
          id: 'br_ipratropium',
          action: 'ADD IPRATROPIUM BROMIDE',
          dose: {
            drug: 'Ipratropium bromide',
            dosePerKg: 0,
            unit: 'mcg',
            route: 'Nebulizer',
            preparation: '<12 years: 250 mcg. ≥12 years: 500 mcg. Mix with salbutamol.',
            frequency: 'Every 20 minutes x3 doses',
          },
          detail: 'Add to salbutamol nebulizer. Synergistic bronchodilation.',
          timer: 1200,
          reassess: 'Is the patient improving?',
          escalateIf: 'Persistent severe wheeze, worsening work of breathing',
        },
        {
          id: 'br_steroids',
          action: 'GIVE SYSTEMIC STEROIDS',
          dose: {
            drug: 'Prednisolone',
            dosePerKg: 1,
            unit: 'mg',
            maxDose: 40,
            route: 'PO (or IV methylprednisolone if unable to swallow)',
            preparation: 'If IV needed: Methylprednisolone 1 mg/kg (max 60mg)',
            frequency: 'Once daily for 3-5 days',
          },
          detail: 'Give early. Takes 4-6 hours to work. Critical for reducing inflammation.',
          critical: true,
        },
        {
          id: 'br_magnesium',
          action: 'IV MAGNESIUM SULFATE',
          dose: {
            drug: 'Magnesium sulfate',
            dosePerKg: 40,
            unit: 'mg',
            maxDose: 2000,
            route: 'IV over 20 minutes',
            preparation: 'Dilute in normal saline. Monitor for hypotension.',
          },
          detail: 'For severe/life-threatening asthma not responding to initial treatment.',
          timer: 1200,
          reassess: 'Is the patient improving?',
          escalateIf: 'Still in severe distress',
          critical: true,
        },
        {
          id: 'br_iv_salbutamol',
          action: 'IV SALBUTAMOL INFUSION',
          dose: {
            drug: 'Salbutamol IV',
            dosePerKg: 5,
            unit: 'mcg/min',
            maxDose: 20,
            route: 'IV continuous infusion',
            preparation: 'Start at 1 mcg/kg/min, increase by 1 mcg/kg/min every 15 min. Max 5 mcg/kg/min.',
          },
          detail: 'ICU-level care. Continuous cardiac monitoring required. Watch for tachycardia, hypokalemia.',
          critical: true,
        },
        {
          id: 'br_intubation_consider',
          action: 'CONSIDER INTUBATION',
          detail: 'Last resort for asthma. Indications: exhaustion, silent chest, decreasing consciousness, respiratory failure despite maximal therapy. Use ketamine for induction (bronchodilator properties).',
          critical: true,
        },
      ],
    },
    {
      id: 'croup',
      name: 'Croup / Upper Airway Obstruction',
      matchCondition: (answers) => answers.stridor === 'yes' && answers.wheezing !== 'yes',
      steps: [
        {
          id: 'cr_calm',
          action: 'KEEP CHILD CALM - MINIMAL HANDLING',
          detail: 'Agitation worsens stridor. Let child sit in parent\'s lap. Do NOT examine throat.',
          critical: true,
        },
        {
          id: 'cr_o2',
          action: 'OXYGEN IF SpO2 < 92%',
          detail: 'Blow-by oxygen if child distressed by mask. Target SpO2 ≥ 94%.',
        },
        {
          id: 'cr_nebulized_epi',
          action: 'NEBULIZED EPINEPHRINE (ADRENALINE)',
          dose: {
            drug: 'Epinephrine (Adrenaline)',
            dosePerKg: 0,
            unit: 'mL',
            route: 'Nebulizer',
            preparation: '0.5 mL/kg of 1:1000 (max 5 mL). Dilute to 3 mL with normal saline.',
            frequency: 'Can repeat every 30 minutes if needed',
          },
          detail: 'Rapid onset (10 min). Effect lasts 2 hours. MUST observe for rebound.',
          timer: 600,
          reassess: 'Is stridor improving?',
          escalateIf: 'Stridor persists at rest, increasing work of breathing',
          critical: true,
        },
        {
          id: 'cr_dexamethasone',
          action: 'GIVE DEXAMETHASONE',
          dose: {
            drug: 'Dexamethasone',
            dosePerKg: 0.6,
            unit: 'mg',
            maxDose: 10,
            route: 'PO/IM/IV',
            preparation: 'Single dose. PO preferred if child can swallow.',
          },
          detail: 'Takes 2-4 hours to work. Single dose is sufficient.',
          critical: true,
        },
        {
          id: 'cr_observe',
          action: 'OBSERVE FOR 4 HOURS',
          detail: 'If nebulized epinephrine given, must observe for rebound stridor. If improving, can discharge with safety-net advice.',
          timer: 14400,
          reassess: 'Is the patient stable for discharge?',
          escalateIf: 'Recurrent stridor, worsening distress',
        },
        {
          id: 'cr_intubation',
          action: 'PREPARE FOR INTUBATION IF WORSENING',
          detail: 'Use ETT 0.5-1 size smaller than age-predicted. Call anesthesia/ENT. This is a difficult airway.',
          critical: true,
        },
      ],
    },
  ],
  defaultSteps: [
    // General respiratory distress (no wheezing, no stridor)
    {
      id: 'rd_o2',
      action: 'HIGH-FLOW OXYGEN',
      detail: 'Non-rebreather mask at 15 L/min. Target SpO2 ≥ 94%. If infant: consider high-flow nasal cannula.',
      critical: true,
    },
    {
      id: 'rd_position',
      action: 'OPTIMIZE POSITION',
      detail: 'Sit upright if conscious. Sniffing position if altered. Suction if secretions visible.',
    },
    {
      id: 'rd_assess_cause',
      action: 'ASSESS FOR CAUSE',
      detail: 'Listen to chest: crackles (pneumonia/pulmonary edema), decreased sounds (effusion/pneumothorax), equal air entry. Check CXR if available.',
      reassess: 'Can you identify the cause?',
    },
    {
      id: 'rd_niv',
      action: 'CONSIDER NON-INVASIVE VENTILATION',
      detail: 'CPAP or BiPAP if available. Start CPAP at 5-7 cmH2O. Useful for bronchiolitis, pneumonia, pulmonary edema.',
    },
    {
      id: 'rd_antibiotics',
      action: 'ANTIBIOTICS IF INFECTION SUSPECTED',
      dose: {
        drug: 'Ceftriaxone',
        dosePerKg: 50,
        unit: 'mg',
        maxDose: 2000,
        route: 'IV',
        preparation: 'Give over 30 minutes. Add vancomycin if MRSA suspected.',
        frequency: 'Once daily',
      },
      detail: 'If fever + crackles + respiratory distress → treat as pneumonia. Don\'t wait for CXR.',
    },
    {
      id: 'rd_intubation',
      action: 'INTUBATE IF FAILING',
      detail: 'Indications: exhaustion, apnea, unable to maintain SpO2 >90% on high-flow O2, decreasing consciousness.',
      critical: true,
    },
  ],
};
