import type { Pathway } from '../stateMachine';

export const shockPathway: Pathway = {
  id: 'shock',
  name: 'Shock / Poor Perfusion',
  icon: '💧',
  description: 'Pale, cold, fast heart rate, poor perfusion',
  clarifyingQuestions: [
    {
      id: 'fever',
      text: 'Does the patient have a fever?',
      options: [
        { label: 'YES - Fever present', value: 'yes' },
        { label: 'NO', value: 'no' },
      ],
    },
    {
      id: 'bleeding',
      text: 'Is there visible bleeding or history of fluid loss?',
      options: [
        { label: 'YES - Bleeding/dehydration', value: 'yes' },
        { label: 'NO', value: 'no' },
      ],
    },
  ],
  subPathways: [
    {
      id: 'septic_shock',
      name: 'Septic Shock',
      matchCondition: (answers) => answers.fever === 'yes',
      steps: [
        {
          id: 'ss_o2',
          action: 'HIGH-FLOW OXYGEN',
          detail: 'Non-rebreather mask at 15 L/min. Target SpO2 ≥ 94%.',
          critical: true,
        },
        {
          id: 'ss_access',
          action: 'IV/IO ACCESS - 2 LARGE BORE LINES',
          detail: 'IO if IV not obtained within 90 seconds. Do NOT delay fluids.',
          critical: true,
        },
        {
          id: 'ss_bolus1',
          action: 'FLUID BOLUS: 20 mL/kg NORMAL SALINE',
          dose: {
            drug: 'Normal Saline 0.9%',
            dosePerKg: 20,
            unit: 'mL',
            route: 'IV/IO push',
            preparation: 'Push as fast as possible. Use 60mL syringe push-pull technique.',
            frequency: 'Repeat up to 60 mL/kg in first hour',
          },
          timer: 300,
          reassess: 'Reassess after bolus: cap refill, heart rate, mental status',
          escalateIf: 'Still tachycardic, still poorly perfused after 40-60 mL/kg',
          critical: true,
        },
        {
          id: 'ss_antibiotics',
          action: 'ANTIBIOTICS WITHIN 1 HOUR',
          dose: {
            drug: 'Ceftriaxone',
            dosePerKg: 80,
            unit: 'mg',
            maxDose: 4000,
            route: 'IV',
            preparation: 'Give over 30 min. If meningitis suspected: add vancomycin 15mg/kg.',
            frequency: 'Once daily (ceftriaxone), every 6h (vancomycin)',
          },
          detail: 'DO NOT DELAY. Every hour of delay increases mortality. Give empirically.',
          critical: true,
        },
        {
          id: 'ss_glucose',
          action: 'CHECK AND CORRECT GLUCOSE',
          dose: {
            drug: 'Dextrose 10%',
            dosePerKg: 5,
            unit: 'mL',
            route: 'IV',
            preparation: 'If glucose < 3 mmol/L (54 mg/dL): give 2-5 mL/kg of D10W.',
          },
          detail: 'Hypoglycemia is common in septic children. Check immediately.',
          critical: true,
        },
        {
          id: 'ss_calcium',
          action: 'CHECK AND CORRECT CALCIUM',
          dose: {
            drug: 'Calcium gluconate 10%',
            dosePerKg: 0.5,
            unit: 'mL',
            maxDose: 20,
            route: 'IV over 10 minutes',
            preparation: 'Give slowly with cardiac monitoring. Ionized calcium < 1.0 mmol/L.',
          },
          detail: 'Hypocalcemia impairs cardiac contractility. Common in sepsis.',
        },
        {
          id: 'ss_vasopressor',
          action: 'START VASOPRESSOR IF FLUID-REFRACTORY',
          dose: {
            drug: 'Epinephrine (Adrenaline)',
            dosePerKg: 0.1,
            unit: 'mcg/kg/min',
            route: 'IV continuous infusion',
            preparation: 'Start at 0.05-0.1 mcg/kg/min. Can give through peripheral IV while central access obtained.',
            frequency: 'Titrate to effect (target MAP, cap refill)',
          },
          detail: 'Cold shock (cold extremities, weak pulse): Epinephrine first-line. Warm shock (warm, bounding pulse): Norepinephrine first-line.',
          critical: true,
        },
        {
          id: 'ss_hydrocortisone',
          action: 'CONSIDER HYDROCORTISONE',
          dose: {
            drug: 'Hydrocortisone',
            dosePerKg: 2,
            unit: 'mg',
            maxDose: 100,
            route: 'IV',
            preparation: 'For catecholamine-resistant shock. Also if adrenal insufficiency suspected.',
            frequency: 'Every 6-8 hours',
          },
          detail: 'Give if shock persists despite fluids AND vasopressors. Absolute indication if known adrenal insufficiency or chronic steroid use.',
        },
      ],
    },
    {
      id: 'hypovolemic_shock',
      name: 'Hypovolemic Shock',
      matchCondition: (answers) => answers.bleeding === 'yes',
      steps: [
        {
          id: 'hs_o2',
          action: 'HIGH-FLOW OXYGEN',
          detail: 'Non-rebreather mask at 15 L/min.',
          critical: true,
        },
        {
          id: 'hs_stop_bleeding',
          action: 'STOP THE BLEEDING',
          detail: 'Direct pressure. Tourniquet if limb hemorrhage not controlled. Pressure dressing.',
          critical: true,
        },
        {
          id: 'hs_access',
          action: 'IV/IO ACCESS - 2 LARGE BORE LINES',
          detail: 'IO if IV not obtained within 90 seconds.',
          critical: true,
        },
        {
          id: 'hs_bolus',
          action: 'FLUID BOLUS: 20 mL/kg NORMAL SALINE',
          dose: {
            drug: 'Normal Saline 0.9%',
            dosePerKg: 20,
            unit: 'mL',
            route: 'IV/IO push',
            preparation: 'Push rapidly. If hemorrhagic: consider blood products early.',
            frequency: 'Reassess after each bolus. Max 40-60 mL/kg crystalloid.',
          },
          timer: 300,
          reassess: 'Reassess perfusion: cap refill, heart rate, blood pressure',
          escalateIf: 'Still hypotensive after 40 mL/kg → consider blood transfusion',
          critical: true,
        },
        {
          id: 'hs_blood',
          action: 'TRANSFUSE IF HEMORRHAGIC',
          dose: {
            drug: 'Packed Red Blood Cells',
            dosePerKg: 10,
            unit: 'mL',
            route: 'IV',
            preparation: 'O-negative if crossmatch not available. Use blood warmer if available.',
            frequency: 'Repeat as needed. Target Hb > 7 g/dL (>10 if ongoing bleeding)',
          },
          detail: 'If hemorrhagic shock: switch to blood early. Don\'t wait for lab results.',
          critical: true,
        },
        {
          id: 'hs_txa',
          action: 'TRANEXAMIC ACID (TXA)',
          dose: {
            drug: 'Tranexamic Acid',
            dosePerKg: 15,
            unit: 'mg',
            maxDose: 1000,
            route: 'IV over 10 minutes',
            preparation: 'Give within 3 hours of injury. Follow with 2 mg/kg/hr infusion.',
          },
          detail: 'Reduces mortality in hemorrhagic shock. Give early.',
        },
      ],
    },
  ],
  defaultSteps: [
    // Undifferentiated shock
    {
      id: 'us_o2',
      action: 'HIGH-FLOW OXYGEN',
      detail: 'Non-rebreather mask at 15 L/min. Target SpO2 ≥ 94%.',
      critical: true,
    },
    {
      id: 'us_access',
      action: 'IV/IO ACCESS',
      detail: 'IO if IV not obtained within 90 seconds.',
      critical: true,
    },
    {
      id: 'us_bolus',
      action: 'FLUID BOLUS: 20 mL/kg NORMAL SALINE',
      dose: {
        drug: 'Normal Saline 0.9%',
        dosePerKg: 20,
        unit: 'mL',
        route: 'IV/IO push',
        preparation: 'Push rapidly.',
        frequency: 'Reassess after each bolus',
      },
      timer: 300,
      reassess: 'Is perfusion improving?',
      escalateIf: 'No improvement after 40-60 mL/kg',
      critical: true,
    },
    {
      id: 'us_glucose',
      action: 'CHECK GLUCOSE',
      dose: {
        drug: 'Dextrose 10%',
        dosePerKg: 5,
        unit: 'mL',
        route: 'IV',
        preparation: 'If glucose < 3 mmol/L: give D10W 2-5 mL/kg',
      },
      detail: 'Always check glucose in a shocked child.',
      critical: true,
    },
    {
      id: 'us_identify',
      action: 'IDENTIFY SHOCK TYPE',
      detail: 'Fever → septic shock (antibiotics). Bleeding/dehydration → hypovolemic (fluids/blood). JVD + muffled sounds → cardiogenic/tamponade. Rash + swelling → anaphylaxis (epinephrine).',
      reassess: 'Can you identify the cause?',
    },
    {
      id: 'us_vasopressor',
      action: 'VASOPRESSOR IF FLUID-REFRACTORY',
      dose: {
        drug: 'Epinephrine (Adrenaline)',
        dosePerKg: 0.1,
        unit: 'mcg/kg/min',
        route: 'IV continuous infusion',
        preparation: 'Start at 0.05-0.1 mcg/kg/min.',
      },
      detail: 'If still hypotensive after 40-60 mL/kg fluids.',
      critical: true,
    },
  ],
};
