import type { Pathway } from '../stateMachine';
import { SPO2_TARGET_RESUS_DETAIL } from '@shared/clinical-spo2-targets';

/** Shock pathways — keep in sync with `docs/clinical-protocols/paediatric-septic-shock.md` (septic_shock) and `docs/clinical-protocols/RESUSGPS_REGISTRY.md`. */
export const shockPathway: Pathway = {
  id: 'shock',
  name: 'Shock / Poor Perfusion',
  icon: '💧',
  description: 'Pale, cold, fast heart rate, poor perfusion',
  clarifyingQuestions: [
    {
      id: 'fever',
      text: 'Does the patient have a fever?',
      options: [
        { label: 'YES - Fever present', value: 'yes' },
        { label: 'NO', value: 'no' },
      ],
    },
    {
      id: 'bleeding',
      text: 'Is there visible bleeding or history of fluid loss?',
      options: [
        { label: 'YES - Bleeding/dehydration', value: 'yes' },
        { label: 'NO', value: 'no' },
      ],
    },
  ],
  subPathways: [
    {
      id: 'septic_shock',
      name: 'Septic Shock',
      matchCondition: (answers) => answers.fever === 'yes',
      steps: [
        {
          id: 'ss_o2',
          action: 'HIGH-FLOW OXYGEN',
          detail: `Give age-, size-, and severity-appropriate oxygen/ventilatory support if hypoxaemic and titrate to the selected clinical target. ${SPO2_TARGET_RESUS_DETAIL}`,
          critical: true,
        },
        {
          id: 'ss_access',
          action: 'IV/IO ACCESS - 2 LARGE BORE LINES',
          detail: 'IO if IV not obtained within 90 seconds. Do NOT delay fluids.',
          critical: true,
        },
        {
          id: 'ss_bolus1',
          action: 'FLUID ALIQUOT: 10 mL/kg NORMAL SALINE',
          dose: {
            drug: 'Normal Saline 0.9%',
            dosePerKg: 10,
            unit: 'mL',
            route: 'IV/IO push',
            preparation: 'Use a small age-, aetiology-, perfusion-, and setting-appropriate aliquot. Reassess after EACH aliquot; in DKA, severe malnutrition, cardiogenic shock, or respiratory failure use the relevant specialist protocol rather than a generic bolus.',
            frequency: 'Do not use a universal cumulative volume; stop for overload or no response and escalate to blood, vasoactive support, or higher-level care as indicated',
          },
          timer: 300,
          reassess: 'Reassess after each aliquot: cap refill, HR, BP, mental status, lung sounds',
          escalateIf: 'Still tachycardic/poorly perfused after 40–60 mL/kg OR signs of fluid overload → vasopressors',
          critical: true,
        },
        {
          id: 'ss_antibiotics',
          action: 'ANTIBIOTICS WITHIN 1 HOUR',
          dose: {
            drug: 'Ceftriaxone',
            dosePerKg: 0,
            doseModel: 'protocol_only',
            unit: 'mg',
            maxDose: 0,
            route: 'IV/IO per selected antimicrobial protocol',
            preparation: 'Use the age-, neonatal-status-, source-, local-resistance-, allergy-, and formulary-specific antimicrobial regimen. If meningitis is suspected, follow the governed meningitis protocol; do not delay treatment for an unsafe LP.',
            frequency: 'Per selected local protocol; document agent, dose, route, time, and reassessment',
          },
          detail: 'Do not delay appropriate antimicrobials when bacterial sepsis is suspected, but select the age-, neonatal-status-, source-, local-resistance-, allergy-, and formulary-specific regimen; do not use a generic ceftriaxone schedule.',
          critical: true,
        },
        {
          id: 'ss_glucose',
          action: 'CHECK AND CORRECT GLUCOSE',
          dose: {
            drug: 'Dextrose 10%',
            dosePerKg: 5,
            unit: 'mL',
            route: 'IV',
            preparation: 'If glucose is low, use the age-, concentration-, route-, and local-hypoglycaemia-protocol-specific dextrose treatment; recheck promptly and do not rely on one universal volume.',
          },
          detail: 'Hypoglycemia is common in septic children. Check immediately.',
          critical: true,
        },
        {
          id: 'ss_calcium',
          action: 'CHECK AND CORRECT CALCIUM',
          dose: {
            drug: 'Calcium gluconate 10%',
            dosePerKg: 0.5,
            unit: 'mL',
            maxDose: 20,
            route: 'IV over 10 minutes',
            preparation: 'Give slowly with cardiac monitoring. Ionized calcium < 1.0 mmol/L.',
          },
          detail: 'Hypocalcemia impairs cardiac contractility. Common in sepsis.',
        },
        {
          id: 'ss_vasopressor',
          action: 'START VASOPRESSOR IF FLUID-REFRACTORY',
          dose: {
            drug: 'Epinephrine (Adrenaline)',
            dosePerKg: 0.1,
            unit: 'mcg/kg/min',
            route: 'IV continuous infusion',
            preparation: 'Start at 0.05-0.1 mcg/kg/min. Can give through peripheral IV while central access obtained.',
            frequency: 'Titrate to effect (target MAP, cap refill)',
          },
          detail: 'Cold shock (cold extremities, weak pulse): Epinephrine first-line. Warm shock (warm, bounding pulse): Norepinephrine first-line.',
          critical: true,
        },
        {
          id: 'ss_hydrocortisone',
          action: 'CONSIDER HYDROCORTISONE',
          dose: {
            drug: 'Hydrocortisone',
            dosePerKg: 2,
            unit: 'mg',
            maxDose: 100,
            route: 'IV',
            preparation: 'For catecholamine-resistant shock. Also if adrenal insufficiency suspected.',
            frequency: 'Every 6-8 hours',
          },
          detail: 'Give if shock persists despite fluids AND vasopressors. Absolute indication if known adrenal insufficiency or chronic steroid use.',
        },
      ],
    },
    {
      id: 'hypovolemic_shock',
      name: 'Hypovolemic Shock',
      matchCondition: (answers) => answers.bleeding === 'yes',
      steps: [
        {
          id: 'hs_o2',
          action: 'HIGH-FLOW OXYGEN',
          detail: 'Give age-, size-, and severity-appropriate oxygen/ventilatory support if hypoxaemic and titrate to the selected clinical target.',
          critical: true,
        },
        {
          id: 'hs_stop_bleeding',
          action: 'STOP THE BLEEDING',
          detail: 'Direct pressure. Tourniquet if limb hemorrhage not controlled. Pressure dressing.',
          critical: true,
        },
        {
          id: 'hs_access',
          action: 'IV/IO ACCESS - 2 LARGE BORE LINES',
          detail: 'IO if IV not obtained within 90 seconds.',
          critical: true,
        },
        {
          id: 'hs_bolus',
          action: 'FLUID ALIQUOT: 10 mL/kg NORMAL SALINE',
          dose: {
            drug: 'Normal Saline 0.9%',
            dosePerKg: 10,
            unit: 'mL',
            route: 'IV/IO push',
            preparation: 'Use a small age-, aetiology-, perfusion-, and setting-appropriate aliquot; reassess after each. Haemorrhage, severe malnutrition, cardiogenic disease, and respiratory failure require their relevant specialist protocol.',
            frequency: 'No universal cumulative volume; stop for overload or no response and escalate to blood or vasoactive support as indicated',
          },
          timer: 300,
          reassess: 'Reassess perfusion: cap refill, heart rate, blood pressure',
          escalateIf: 'If perfusion remains poor or haemorrhage continues after an appropriate aliquot, escalate promptly under the age- and setting-specific haemorrhage/transfusion protocol.',
          critical: true,
        },
        {
          id: 'hs_blood',
          action: 'TRANSFUSE IF HEMORRHAGIC',
          dose: {
            drug: 'Packed Red Blood Cells',
            dosePerKg: 10,
            unit: 'mL',
            route: 'IV',
            preparation: 'Use emergency blood or component therapy only under the local age- and setting-specific transfusion protocol with compatibility, warming, monitoring, and senior oversight.',
            frequency: 'Dose and target are indication-, age-, bleeding-, and protocol-specific; do not use a universal haemoglobin target',
          },
          detail: 'If haemorrhagic shock is suspected, activate the local age- and setting-specific haemorrhage/transfusion protocol early; do not use a universal product, ratio, or target.',
          critical: true,
        },
        {
          id: 'hs_txa',
          action: 'TRANEXAMIC ACID (TXA)',
          dose: {
            drug: 'Tranexamic Acid',
            dosePerKg: 15,
            unit: 'mg',
            maxDose: 1000,
            route: 'IV over 10 minutes',
            preparation: 'Consider TXA only under the age-, weight-, timing-, injury-, contraindication-, and local haemorrhage-protocol regimen; do not infer an adult infusion schedule.',
          },
          detail: 'Consider TXA only when the age-, weight-, timing-, injury-, contraindication-, and local haemorrhage-protocol criteria are met.',
        },
      ],
    },
  ],
  defaultSteps: [
    // Undifferentiated shock
    {
      id: 'us_o2',
      action: 'HIGH-FLOW OXYGEN',
        detail: `Give age-, size-, and severity-appropriate oxygen/ventilatory support if hypoxaemic and titrate to the selected clinical target. ${SPO2_TARGET_RESUS_DETAIL}`,
      critical: true,
    },
    {
      id: 'us_access',
      action: 'IV/IO ACCESS',
      detail: 'IO if IV not obtained within 90 seconds.',
      critical: true,
    },
    {
      id: 'us_bolus',
      action: 'FLUID ALIQUOT: 10 mL/kg NORMAL SALINE',
      dose: {
        drug: 'Normal Saline 0.9%',
        dosePerKg: 10,
        unit: 'mL',
        route: 'IV/IO push',
        preparation: 'Use a small age-, aetiology-, perfusion-, and setting-appropriate aliquot. Reassess perfusion, BP, CRT, lungs, and hepatomegaly after each; use the DKA, severe-malnutrition, cardiogenic, or respiratory-failure protocol when relevant.',
        frequency: 'Do not use a universal cumulative volume; stop for overload or no response and escalate to blood, vasoactive support, or higher-level care as indicated',
      },
      timer: 300,
      reassess: 'Is perfusion improving? Any crackles, hepatomegaly, or rising work of breathing?',
      escalateIf: 'No improvement or signs of overload after an appropriate aliquot → stop, reassess the shock phenotype, and escalate under the relevant age- and setting-specific protocol.',
      critical: true,
    },
    {
      id: 'us_glucose',
      action: 'CHECK GLUCOSE',
      dose: {
        drug: 'Dextrose 10%',
        dosePerKg: 5,
        unit: 'mL',
        route: 'IV',
        preparation: 'If glucose < 3 mmol/L: give D10W 2-5 mL/kg',
      },
      detail: 'Always check glucose in a shocked child.',
      critical: true,
    },
    {
      id: 'us_identify',
      action: 'IDENTIFY SHOCK TYPE',
      detail: 'Fever → septic shock (antibiotics). Bleeding/dehydration → hypovolemic (fluids/blood). JVD + muffled sounds → cardiogenic/tamponade. Rash + swelling → anaphylaxis (epinephrine).',
      reassess: 'Can you identify the cause?',
    },
    {
      id: 'us_vasopressor',
      action: 'VASOPRESSOR IF FLUID-REFRACTORY',
      dose: {
        drug: 'Epinephrine (Adrenaline)',
        dosePerKg: 0.1,
        unit: 'mcg/kg/min',
        route: 'IV continuous infusion',
        preparation: 'Start at 0.05-0.1 mcg/kg/min.',
      },
      detail: 'If still hypotensive after 40-60 mL/kg fluids.',
      critical: true,
    },
  ],
};
