CREATE TABLE `providerPerformanceMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`period` enum('daily','weekly','monthly','yearly') NOT NULL,
	`decisionsLogged` int DEFAULT 0,
	`diagnosticAccuracy` decimal(5,2) DEFAULT '0',
	`avgDecisionTime` int,
	`protocolAdherence` decimal(5,2) DEFAULT '0',
	`patientSurvivalRate` decimal(5,2) DEFAULT '0',
	`livesSavedCount` int DEFAULT 0,
	`patientsMonitoredCount` int DEFAULT 0,
	`coursesCompleted` int DEFAULT 0,
	`certificationsEarned` int DEFAULT 0,
	`referralsMade` int DEFAULT 0,
	`earnings` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `providerPerformanceMetrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `providerProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`licenseNumber` varchar(255),
	`licenseExpiry` timestamp,
	`specialization` varchar(255),
	`yearsOfExperience` int,
	`facilityName` varchar(255),
	`facilityType` enum('primary_health_center','health_post','district_hospital','private_clinic','ngo_clinic','other'),
	`facilityRegion` varchar(255),
	`facilityCountry` varchar(255) DEFAULT 'Kenya',
	`facilityPhone` varchar(20),
	`facilityEmail` varchar(320),
	`averagePatientLoad` int,
	`profileCompleted` boolean DEFAULT false,
	`profileCompletionPercentage` int DEFAULT 0,
	`bio` text,
	`certifications` text,
	`languages` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `providerProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `providerProfiles_userId_unique` UNIQUE(`userId`)
);
