import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export default function AdminProfessionalProgressCorrections() {
  const [status, setStatus] = useState<"open" | "under_review" | "resolved" | "rejected">("open");
  const cases = trpc.professionalProgress.listCorrectionCasesForReview.useQuery({ status });
  const resolveCase = trpc.professionalProgress.resolveCorrectionCase.useMutation({ onSuccess: () => cases.refetch() });
  return <main className="min-h-screen bg-muted/20 px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Administration</p><h1 className="mt-2 text-3xl font-bold">Professional record corrections</h1><p className="mt-2 text-muted-foreground">Review missing, duplicate, identity, certificate, status, and date corrections. Resolve only after checking the authoritative source record.</p></div><Card><CardContent className="flex flex-wrap gap-2 pt-5">{(["open", "under_review", "resolved", "rejected"] as const).map(value => <Button key={value} variant={status === value ? "default" : "outline"} onClick={() => setStatus(value)}>{value.replaceAll("_", " ")}</Button>)}</CardContent></Card><Card><CardHeader><CardTitle>{status.replaceAll("_", " ")} cases</CardTitle><CardDescription>Do not edit certificates or learning evidence solely from a learner request. Record the resolution and preserve the original history.</CardDescription></CardHeader><CardContent className="space-y-4">{cases.isLoading ? <p>Loading correction cases…</p> : !cases.data?.length ? <p className="text-sm text-muted-foreground">No cases in this queue.</p> : cases.data.map(({ case: item, userName, userEmail }) => <div key={item.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">#{item.id} · {item.subject}</p><p className="text-sm text-muted-foreground">{userName} · {userEmail} · {item.category.replaceAll("_", " ")}</p></div><Badge>{item.status.replaceAll("_", " ")}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm">{item.description}</p>{item.evidenceReference ? <p className="mt-2 break-all text-xs text-muted-foreground">Evidence: {item.evidenceReference}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={resolveCase.isPending} onClick={() => resolveCase.mutate({ caseId: item.id, status: "under_review", resolutionNote: "Case received and placed under review." })}>Mark under review</Button><Button size="sm" disabled={resolveCase.isPending} onClick={() => resolveCase.mutate({ caseId: item.id, status: "resolved", resolutionNote: "Resolved after authoritative record review." })}>Resolve</Button><Button size="sm" variant="destructive" disabled={resolveCase.isPending} onClick={() => resolveCase.mutate({ caseId: item.id, status: "rejected", resolutionNote: "Rejected after authoritative record review; see case history." })}>Reject</Button></div></div>)}</CardContent></Card></div></main>;
}
