import { useMemo, useState } from "react";
import { Link, useRoute, useSearch } from "wouter";
import { AlertCircle, CheckCircle2, FileCheck2, Printer, Target } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { PerformanceDashboard } from "./PerformanceDashboard";
import ProviderRecords from "./ProviderRecords";

function periodDates() {
  const now = new Date();
  const end = now.toISOString().slice(0, 10);
  const start = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
  return { start, end };
}

function MetricCard({ title, value, detail, tone = "teal", progressValue }: { title: string; value: number | string; detail: string; tone?: "teal" | "indigo" | "amber"; progressValue?: number }) {
  const colour = tone === "indigo" ? "text-indigo-700" : tone === "amber" ? "text-amber-700" : "text-teal-700";
  const percentage = progressValue ?? (typeof value === "number" ? value : undefined);
  return <Card className="print:break-inside-avoid print:border-slate-300 print:shadow-none"><CardHeader className="pb-2"><CardDescription>{title}</CardDescription><CardTitle className={`text-3xl ${colour}`}>{typeof value === "number" ? `${value}%` : value}</CardTitle></CardHeader><CardContent>{percentage === undefined ? <div className="h-2" aria-hidden="true" /> : <Progress value={percentage} className="h-2" />}<p className="mt-2 text-xs text-muted-foreground">{detail}</p></CardContent></Card>;
}

type PortfolioSection = "overview" | "progress" | "records";

function getPortfolioSection(search: string): PortfolioSection {
  const value = new URLSearchParams(search).get("section");
  return value === "overview" || value === "records" ? value : "progress";
}

export default function ProfessionalProgressPage() {
  const search = useSearch();
  const section = getPortfolioSection(search);
  const sectionLink = (value: PortfolioSection) => `/my-progress?section=${value}`;
  const [, verifyParams] = useRoute("/verify-progress/:verificationCode");
  const { user, loading } = useAuth({ redirectOnUnauthenticated: !verifyParams, redirectPath: "/login?next=%2Fmy-progress" });
  const defaults = useMemo(periodDates, []);
  const [periodType, setPeriodType] = useState<"monthly" | "quarterly" | "annual">("monthly");
  const [reportScope, setReportScope] = useState<"activity" | "current_status">("activity");
  const [periodStart, setPeriodStart] = useState(defaults.start);
  const [periodEnd, setPeriodEnd] = useState(defaults.end);
  const [goalTitle, setGoalTitle] = useState("");
  const [goalTarget, setGoalTarget] = useState("1");
  const [verifiedCode, setVerifiedCode] = useState<string | null>(null);
  const [verifiedReportId, setVerifiedReportId] = useState<number | null>(null);
  const [correctionCategory, setCorrectionCategory] = useState("missing_record");
  const [correctionSubject, setCorrectionSubject] = useState("");
  const [correctionEvidenceReference, setCorrectionEvidenceReference] = useState("");
  const [correctionDescription, setCorrectionDescription] = useState("");
  const [pdfError, setPdfError] = useState<string | null>(null);
  const reportInput = { reportType: periodType, reportScope, periodStart, periodEnd } as const;
  const reportQuery = trpc.professionalProgress.getMyReport.useQuery(reportInput, { enabled: Boolean(user && !verifyParams && section === "progress"), retry: false });
  const latestReportQuery = trpc.professionalProgress.getLatestVerifiedReport.useQuery(reportInput, { enabled: Boolean(user && !verifyParams && section === "progress"), retry: false });
  const evidenceQuery = trpc.professionalProgress.getMyEvidenceLedger.useQuery(reportInput, { enabled: Boolean(user && !verifyParams && section === "progress"), retry: false });
  const goalsQuery = trpc.professionalProgress.listMyGoals.useQuery(undefined, { enabled: Boolean(user && !verifyParams && section === "progress"), retry: false });
  const correctionCasesQuery = trpc.professionalProgress.listMyCorrectionCases.useQuery(undefined, { enabled: Boolean(user && !verifyParams && section === "progress"), retry: false });
  const verifyQuery = trpc.professionalProgress.verifyReport.useQuery({ verificationCode: verifyParams?.verificationCode ?? "" }, { enabled: Boolean(verifyParams?.verificationCode), retry: false });
  const utils = trpc.useUtils();
  const createReport = trpc.professionalProgress.createVerifiedReport.useMutation({ onSuccess: result => { setVerifiedCode(result.verificationCode); setVerifiedReportId(result.reportId); void utils.professionalProgress.getLatestVerifiedReport.invalidate(reportInput); } });
  const createGoal = trpc.professionalProgress.createGoal.useMutation({ onSuccess: async () => { setGoalTitle(""); await goalsQuery.refetch(); } });
  const createCorrectionCase = trpc.professionalProgress.createCorrectionCase.useMutation({ onSuccess: async () => { setCorrectionSubject(""); setCorrectionEvidenceReference(""); setCorrectionDescription(""); await correctionCasesQuery.refetch(); } });
  const downloadProfessionalReport = async () => {
    setPdfError(null);
    try {
      const result = latestReportQuery.data;
      if (!result) {
        setPdfError("No signed snapshot exists for this period. Create a verifiable snapshot first, then download it.");
        return;
      }
      setVerifiedCode(result.verificationCode);
      setVerifiedReportId(result.id);
      // Let the browser handle the authenticated PDF response and its
      // Content-Disposition header directly. This avoids blob downloads being
      // blocked or discarded by mobile browsers after an awaited mutation.
      const anchor = document.createElement("a");
      anchor.href = result.pdfUrl;
      anchor.rel = "noreferrer";
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
    } catch (error) {
      setPdfError(error instanceof Error ? error.message : "The report PDF could not be downloaded. Please try again.");
    }
  };

  if (section !== "progress" && !verifyParams) {
    return <main className="min-h-screen bg-muted/20 px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Individual Platform</p><h1 className="mt-2 text-3xl font-bold">My Professional Portfolio</h1><p className="mt-2 max-w-3xl text-muted-foreground">One trusted home for your progress, goals, reports, certificates, CPD, and professional evidence.</p></div><nav aria-label="Professional portfolio sections" className="grid gap-2 rounded-xl border bg-background p-2 sm:grid-cols-3"><Link href={sectionLink("overview")} className={`rounded-lg px-3 py-3 text-sm font-semibold ${section === "overview" ? "bg-primary text-primary-foreground" : "hover:bg-muted"}`}>Overview<span className="mt-1 block text-xs font-normal opacity-80">Personal activity and trends</span></Link><Link href={sectionLink("progress")} className="rounded-lg px-3 py-3 text-sm font-semibold hover:bg-muted">Progress, goals &amp; reports<span className="mt-1 block text-xs font-normal opacity-80">Learning status and printable reports</span></Link><Link href={sectionLink("records")} className={`rounded-lg px-3 py-3 text-sm font-semibold ${section === "records" ? "bg-primary text-primary-foreground" : "hover:bg-muted"}`}>Certificates &amp; records<span className="mt-1 block text-xs font-normal opacity-80">CPD, certificates and evidence</span></Link></nav>{section === "overview" ? <PerformanceDashboard embedded /> : <ProviderRecords embedded />}</div></main>;
  }

  if (verifyParams) {
    const verified = verifyQuery.data;
    return <main className="min-h-screen bg-muted/20 px-4 py-10"><Card className="mx-auto max-w-3xl"><CardHeader><CardTitle className="flex items-center gap-2"><FileCheck2 className="h-5 w-5 text-teal-700" />Professional progress verification</CardTitle><CardDescription>Public verification of a minimum-disclosure learning and evidence snapshot.</CardDescription></CardHeader><CardContent>{verifyQuery.isLoading ? <p>Checking verification record…</p> : verified?.verified ? <div className="space-y-4"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="h-5 w-5" />Verified snapshot · status {String(verified.status ?? "active").toUpperCase()}</div><p className="text-sm text-muted-foreground">Report ID: {verified.reportId}</p><p><strong>{verified.subjectName}</strong> · {verified.cadre || "Provider"}</p><p className="text-sm text-muted-foreground">{verified.reportType} report · {String(verified.periodStart)} to {String(verified.periodEnd)}</p><p className="text-sm text-muted-foreground">Public validity: {verified.publicExpiresAt ? `until ${String(verified.publicExpiresAt)}` : "not specified"}</p><p className="break-all rounded bg-muted p-3 font-mono text-xs">SHA-256: {verified.snapshotHash}</p><Button onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Print verified record</Button></div> : <div className="flex items-center gap-2 text-red-700"><AlertCircle className="h-5 w-5" />This progress record could not be verified. It may be expired, revoked, or superseded.</div>}</CardContent></Card></main>;
  }

  if (loading || !user || reportQuery.isLoading) return <main className="p-8 text-center">Loading your professional progress…</main>;
  if (reportQuery.isError) return <main className="p-8 text-center text-red-700">Your progress record could not be loaded. No learning data was changed.</main>;
  const report = reportQuery.data as any;
  if (!report) return <main className="p-8 text-center">No progress record is available for this period yet.</main>;
  const lifeSupport = report.lifeSupport as Array<{ program: string; source: string; phase: string; percentage: number; dataQuality?: { level: string; reasons: string[] }; nextAction?: { destination: string; label: string; phase: string } }>;
  const externalCompletions = (report.externalCompletions ?? []) as Array<{ program: string; source: string; phase: string; percentage: number }>;
  const pathways = (report.pathways ?? []) as Array<{ program: string; source: string; phase: string; percentage: number; status: string; paymentStatus?: string | null; nextAction?: { destination: string; label: string; phase: string } }>;
  const continuationFor = (program: string) => lifeSupport.find((item) => item.program === program)?.nextAction;
  const fellowship = report.fellowship?.overallPercentage ?? 0;
  return <><style>{`@media print { @page { size: A4; margin: 14mm 12mm; } body { background: #fff !important; } }`}</style><main className="min-h-screen bg-muted/20 px-4 py-8 md:px-8 print:m-0 print:bg-white print:p-0"><div className="mx-auto max-w-6xl space-y-6 print:max-w-none print:space-y-4"><div className="hidden print:flex print:items-start print:justify-between print:border-b-2 print:border-teal-800 print:pb-4"><div className="flex items-center gap-3"><img src="/paeds-resus-logo-brand.png" alt="Paeds Resus" className="h-12 w-auto object-contain" /><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-800">Paeds Resus</p><h1 className="text-2xl font-bold text-slate-950">Professional Progress Report</h1><p className="text-xs text-slate-600">Private professional record · Generated {new Date().toLocaleDateString()}</p></div></div><div className="text-right text-xs text-slate-600"><p className="font-semibold text-slate-900">{user.name}</p><p>{user.cadre || "Healthcare provider"}</p><p>{periodType} · {periodStart} to {periodEnd}</p></div></div><div className="flex flex-wrap items-start justify-between gap-3 print:hidden"><div><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">My Professional Portfolio</p><h1 className="mt-2 text-3xl font-bold">Progress, goals &amp; reports</h1><p className="mt-2 text-muted-foreground">Your life-support, Fellowship, CPD, goals, certificates, and verifiable professional report in one place.</p></div><div className="flex flex-wrap gap-2 print:hidden"><Button asChild variant="outline"><Link href={sectionLink("overview")}>Overview</Link></Button><Button asChild variant="outline"><Link href={sectionLink("records")}>Certificates &amp; records</Link></Button><Button variant="outline" onClick={downloadProfessionalReport} disabled={!latestReportQuery.data || latestReportQuery.isLoading}><FileCheck2 className="mr-2 h-4 w-4" />{latestReportQuery.isLoading ? "Checking signed report…" : "Download signed PDF"}</Button></div></div>
    <Card className="print:hidden"><CardContent className="flex flex-wrap items-end gap-3 pt-5"><label className="text-sm">Report type<select className="mt-1 block h-10 rounded-md border bg-background px-3" value={periodType} onChange={e => setPeriodType(e.target.value as typeof periodType)}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></select></label><label className="text-sm">What should this report show?<select className="mt-1 block h-10 rounded-md border bg-background px-3" value={reportScope} onChange={e => setReportScope(e.target.value as typeof reportScope)}><option value="activity">Activity during this period</option><option value="current_status">Current status now</option></select></label><label className="text-sm">From<Input type="date" value={periodStart} onChange={e => setPeriodStart(e.target.value)} /></label><label className="text-sm">To<Input type="date" value={periodEnd} onChange={e => setPeriodEnd(e.target.value)} /></label><Button onClick={() => reportQuery.refetch()}>Refresh record</Button><Button variant="secondary" onClick={() => createReport.mutate(reportInput)} disabled={createReport.isPending}><FileCheck2 className="mr-2 h-4 w-4" />{createReport.isPending ? "Signing…" : "Create verifiable snapshot"}</Button></CardContent></Card>
    <Card className="print:break-inside-avoid print:border-slate-300 print:shadow-none"><CardContent className="pt-5 text-sm text-muted-foreground"><strong className="text-foreground">Report scope:</strong> {report.reportScope === "current_status" ? "Current status at the time of generation." : "Activity recorded during the selected period."}<br /><strong className="text-foreground">How to read this report:</strong> {report.periodSemantics}<br /><strong className="text-foreground">Evidence rule:</strong> learning completion, assessment, credentials, and observed competence are separate states.</CardContent></Card>
    {evidenceQuery.data?.nextBestAction ? <Card className="border-teal-200 bg-teal-50 print:break-inside-avoid"><CardHeader className="pb-2"><CardTitle className="text-teal-950">Your next best professional action</CardTitle><CardDescription className="text-teal-900">One clear action is more useful than another score.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-teal-950">{evidenceQuery.data.nextBestAction.label}</p><p className="mt-1 text-sm text-teal-900">{(evidenceQuery.data.nextBestAction as any).why ?? (evidenceQuery.data.nextBestAction as any).reason ?? "Continue your professional development."}</p><p className="mt-1 text-xs text-teal-800">Evidence trigger: {(evidenceQuery.data.nextBestAction as any).evidenceTrigger ?? "Current portfolio status"}. Outcome: {(evidenceQuery.data.nextBestAction as any).outcome ?? "Progress is recorded in the Evidence Ledger."}</p></div><Button asChild><a href={(evidenceQuery.data.nextBestAction as any).href || (evidenceQuery.data.nextBestAction as any).destination || "/my-progress?section=development"}>Open next action</a></Button></div></CardContent></Card> : null}
    {report.readinessBottleneck ? <Card className="border-amber-300 bg-amber-50 print:break-inside-avoid"><CardHeader className="pb-2"><CardTitle className="text-amber-950">Readiness / development bottleneck</CardTitle><CardDescription className="text-amber-900">This is the most important unresolved requirement, not a composite readiness score.</CardDescription></CardHeader><CardContent><p className="font-semibold text-amber-950">{report.readinessBottleneck.label}</p><p className="mt-1 text-sm text-amber-900">Current state: {report.readinessBottleneck.currentState}</p><p className="mt-1 text-xs text-amber-800">Evidence: {report.readinessBottleneck.evidence}</p></CardContent></Card> : null}
    {evidenceQuery.data?.evidence?.length ? <Card className="print:break-inside-avoid"><CardHeader><CardTitle>Evidence ledger</CardTitle><CardDescription>{evidenceQuery.data.trustStatement}</CardDescription></CardHeader><CardContent className="space-y-3">{evidenceQuery.data.evidence.slice(0, 12).map((item: any) => <div key={item.sourceKey} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.sourceSystem} · {item.evidenceStrength} · {item.sourceRecordType} #{item.sourceRecordId}</p></div><Badge variant={item.status === "learning_complete" || item.status === "issued" || item.status === "attendance_verified" ? "default" : "secondary"}>{item.status.replaceAll("_", " ")}</Badge></div>)}</CardContent></Card> : null}
    {verifiedCode ? <Card className="border-emerald-200 bg-emerald-50 print:hidden"><CardContent className="pt-5"><p className="font-semibold text-emerald-900">Snapshot created and signed for verification.</p><p className="mt-1 text-xs text-emerald-900">Report ID: {verifiedReportId ?? "—"}</p><p className="mt-1 break-all font-mono text-xs">{window.location.origin}/verify-progress/{verifiedCode}</p><p className="mt-2 text-sm text-emerald-800">Print this page now, or share the verification link with an interviewer, appraiser, or recommender.</p></CardContent></Card> : null}
    {pdfError ? <Card className="border-red-200 bg-red-50 print:hidden"><CardContent className="flex items-start gap-2 pt-5 text-sm text-red-800"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />{pdfError}</CardContent></Card> : null}
    <div className="grid gap-4 md:grid-cols-4"><MetricCard title="Life-support evidence" value={lifeSupport.length} detail="Individual BLS, ACLS, PALS, and NRP records; no aggregate readiness score" tone="teal" progressValue={undefined} /><MetricCard title="NERP / IERP pathways" value={pathways.length} detail={`${pathways.length} pathway record(s); open each record for phase status`} tone="indigo" progressValue={undefined} /><MetricCard title="Fellowship coursework" value={fellowship} detail="Learning progress remains separate from certification and competence" tone="indigo" /><MetricCard title="CPD learning activity" value={`${report.cpd.points} pts`} detail={`${report.cpd.verifiedSessions} verified session(s); points are not a competence percentage`} tone="amber" progressValue={undefined} /></div>
    <Card className="print:hidden"><CardHeader><CardTitle>Continue where you left off</CardTitle><CardDescription>Each AHA card opens the next unfinished phase: cognitive learning, practical booking, or certificates.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link href={continuationFor("BLS")?.destination ?? "/training/bls"} className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 transition hover:border-emerald-400"><p className="font-semibold text-emerald-900">BLS</p><p className="text-xs text-emerald-800">{continuationFor("BLS")?.label ?? "Open BLS learning"} →</p></Link><Link href={continuationFor("ACLS")?.destination ?? "/training/acls"} className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 transition hover:border-emerald-400"><p className="font-semibold text-emerald-900">ACLS</p><p className="text-xs text-emerald-800">{continuationFor("ACLS")?.label ?? "Open ACLS learning"} →</p></Link><Link href={continuationFor("PALS")?.destination ?? "/training/pals"} className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 transition hover:border-emerald-400"><p className="font-semibold text-emerald-900">PALS</p><p className="text-xs text-emerald-800">{continuationFor("PALS")?.label ?? "Open PALS learning"} →</p></Link><Link href={continuationFor("NRP")?.destination ?? "/training/nrp"} className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 transition hover:border-emerald-400"><p className="font-semibold text-emerald-900">NRP</p><p className="text-xs text-emerald-800">{continuationFor("NRP")?.label ?? "Open NRP learning"} →</p></Link><Link href={sectionLink("records")} className="rounded-lg border border-blue-200 bg-blue-50 p-3 transition hover:border-blue-400"><p className="font-semibold text-blue-900">CPD records</p><p className="text-xs text-blue-800">Open sessions and certificates →</p></Link><Link href={sectionLink("progress")} className="rounded-lg border border-violet-200 bg-violet-50 p-3 transition hover:border-violet-400"><p className="font-semibold text-violet-900">Fellowship</p><p className="text-xs text-violet-800">Continue Fellowship →</p></Link><Link href="/care-signal" className="rounded-lg border border-amber-200 bg-amber-50 p-3 transition hover:border-amber-400"><p className="font-semibold text-amber-900">Care Signal</p><p className="text-xs text-amber-800">Report and review clinical learning →</p></Link><Link href="/code-signal" className="rounded-lg border border-amber-200 bg-amber-50 p-3 transition hover:border-amber-400"><p className="font-semibold text-amber-900">Code Signal</p><p className="text-xs text-amber-800">Open code-event reporting →</p></Link></CardContent></Card>
    <Card><CardHeader><CardTitle>Life-support progress</CardTitle><CardDescription>Learning percentage describes recorded learning activity only. It is not competence or readiness.</CardDescription></CardHeader><CardContent className="space-y-4">{lifeSupport.length ? lifeSupport.map((item: any, index: number) => <div key={`${item.program}-${index}`} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{item.program} · {item.source}</p><p className="text-sm text-muted-foreground">{item.phase} · {String(item.recordStatus).replaceAll("_", " ")}</p></div><Badge>{item.percentage}% learning complete</Badge></div><Progress value={item.percentage} className="mt-3 h-2" />{item.dataQuality?.level !== "linked" ? <div className="mt-3 rounded-md border border-amber-300 bg-amber-50 p-2 text-xs text-amber-900"><strong>Record linkage partial.</strong> {item.dataQuality?.reasons?.join(" ") || "The source record is incomplete."}</div> : null}{item.nextAction ? <Link href={item.nextAction.destination} className="mt-2 inline-flex text-sm font-semibold text-teal-700 hover:underline">{item.nextAction.label} →</Link> : null}</div>) : <p className="text-sm text-muted-foreground">No life-support pathway record is linked to this account yet. If you completed training elsewhere, open a correction case below so the team can link the evidence.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>External completion evidence</CardTitle><CardDescription>These records were completed outside the Paeds Resus pathway and are labelled separately as external evidence. No progress percentage is used for this claim.</CardDescription></CardHeader><CardContent className="space-y-4">{externalCompletions.length ? externalCompletions.map((item, index) => <div key={`${item.program}-${index}`} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{item.program} · {item.source}</p><p className="text-sm text-muted-foreground">{item.phase}</p></div><Badge>External evidence · source verified</Badge></div></div>) : <p className="text-sm text-muted-foreground">No external completion evidence is recorded.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Programme pathway status</CardTitle><CardDescription>NERP and IERP progression is separate from individual BLS, ACLS, PALS, and NRP course completion.</CardDescription></CardHeader><CardContent className="space-y-4">{pathways.length ? pathways.map((item, index) => <div key={`${item.program}-${index}`} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{item.program} · {item.source}</p><p className="text-sm text-muted-foreground">{item.phase} · {item.status}{item.paymentStatus ? ` · payment ${item.paymentStatus}` : ""}</p></div><Badge>{item.percentage}% pathway progress</Badge></div><Progress value={item.percentage} className="mt-3 h-2" />{item.nextAction ? <Link href={item.nextAction.destination} className="mt-3 inline-flex text-sm font-semibold text-indigo-700 hover:underline">{item.nextAction.label} →</Link> : null}</div>) : <p className="text-sm text-muted-foreground">No NERP or IERP pathway is linked to this account.</p>}</CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Verified CPD record</CardTitle><CardDescription>Only attendance marked attendance verified contributes to this record.</CardDescription></CardHeader><CardContent>{report.cpd.sessions.length ? <div className="space-y-3">{report.cpd.sessions.map((session: any, index: number) => <div key={`${session.title}-${index}`} className="flex justify-between border-b pb-2 text-sm"><span>{session.title}<br /><span className="text-muted-foreground">{String(session.date)}</span></span><span className="font-medium">{session.points} pts</span></div>)}</div> : <p className="text-sm text-muted-foreground">No verified CPD attendance in this period.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5" />Professional goals</CardTitle><CardDescription>Set a measurable target for your next appraisal period.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-2 print:hidden"><Input placeholder="e.g. Complete 2 CPD sessions" value={goalTitle} onChange={e => setGoalTitle(e.target.value)} /><Input className="w-24" type="number" min="1" value={goalTarget} onChange={e => setGoalTarget(e.target.value)} /><Button disabled={!goalTitle.trim() || createGoal.isPending} onClick={() => createGoal.mutate({ metricKey: "cpd_sessions", title: goalTitle, targetValue: Number(goalTarget), unit: "sessions", periodType, periodStart, periodEnd })}>Set</Button></div>{goalsQuery.data?.length ? goalsQuery.data.map(goal => { const actual = Number((goal as any).actualValue ?? 0); const target = Number(goal.targetValue); const progress = Number((goal as any).progressValue ?? 0); const status = (goal as any).computedStatus ?? goal.status; return <div key={goal.id} className="rounded border p-3 text-sm"><div className="flex items-start justify-between gap-2"><p className="font-medium">{goal.title}</p><Badge variant={status === "achieved" ? "default" : status === "at_risk" || status === "expired" ? "destructive" : "secondary"}>{String(status).replaceAll("_", " ")}</Badge></div><p className="text-muted-foreground">Actual: {actual} / {target} {goal.unit} · {progress}% · {Math.max(0, target - actual)} remaining</p><Progress value={progress} className="mt-2 h-2" /></div>; }) : <p className="text-sm text-muted-foreground">No active goals yet.</p>}</CardContent></Card></div>
    <Card className="print:break-before-page print:break-inside-avoid print:border-slate-300 print:shadow-none"><CardHeader><CardTitle>Certificates and evidence</CardTitle><CardDescription>Certificates remain individually verifiable; this record links them into your period summary.</CardDescription></CardHeader><CardContent>{report.certificates.length ? <div className="grid gap-2 md:grid-cols-2">{report.certificates.map((cert: any) => <div key={cert.verificationCode || cert.certificateNumber} className="rounded border p-3 text-sm"><p className="font-medium">{String(cert.programType).replaceAll("_", " ")}</p><p className="text-muted-foreground">{cert.certificateNumber || "Certificate number pending"}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No certificates issued yet.</p>}</CardContent></Card>
    <Card className="print:hidden"><CardHeader><CardTitle>Something is missing or wrong?</CardTitle><CardDescription>Submit one correction case instead of creating duplicate records. A reviewer can link evidence, resolve duplicates, or explain why a record cannot be changed.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><select className="h-10 rounded-md border bg-background px-3" value={correctionCategory} onChange={e => setCorrectionCategory(e.target.value)}><option value="missing_record">Missing record</option><option value="duplicate_record">Duplicate record</option><option value="wrong_identity">Wrong person or identity</option><option value="wrong_certificate">Wrong certificate</option><option value="wrong_status">Wrong status</option><option value="wrong_date">Wrong date</option><option value="other">Other</option></select><Input placeholder="Short subject" value={correctionSubject} onChange={e => setCorrectionSubject(e.target.value)} /><Input placeholder="Evidence link or reference (optional)" value={correctionEvidenceReference} onChange={e => setCorrectionEvidenceReference(e.target.value)} /></div><textarea className="min-h-24 w-full rounded-md border bg-background p-3 text-sm" placeholder="Describe what should be corrected and what evidence supports it." value={correctionDescription} onChange={e => setCorrectionDescription(e.target.value)} /><Button disabled={createCorrectionCase.isPending || correctionSubject.trim().length < 3 || correctionDescription.trim().length < 10} onClick={() => createCorrectionCase.mutate({ category: correctionCategory as any, subject: correctionSubject, description: correctionDescription, evidenceReference: correctionEvidenceReference || undefined })}>Submit correction case</Button>{correctionCasesQuery.data?.length ? <div className="space-y-2 pt-2"><p className="text-sm font-semibold">Your submitted cases</p>{correctionCasesQuery.data.map(item => <div key={item.id} className="rounded border p-2 text-sm"><span className="font-medium">#{item.id} · {item.subject}</span><span className="ml-2 text-muted-foreground">{item.status.replaceAll("_", " ")}</span></div>)}</div> : null}</CardContent></Card>
    <footer className="hidden print:block print:border-t print:border-slate-300 print:pt-3 print:text-xs print:text-slate-600"><div className="flex items-center justify-between gap-4"><span>Paeds Resus · Professional learning record</span><span>For verification, use the platform verification link or certificate number.</span></div></footer>
  </div></main></>;
}
