/**
 * Emergency Protocols Content
 * 5 protocols covering common pediatric emergencies: Diarrhea, Pneumonia, Malaria, Meningitis, Shock
 */

export const emergencyProtocolsContent = {
  diarrhea: {
    protocol: {
      name: "Severe Dehydrating Diarrhea",
      category: "diarrhea",
      description: "Management of severe acute diarrhea with dehydration in children",
      ageMin: 0,
      ageMax: 216, // 0-18 years
      severity: "severe",
      estimatedMortality: 2.5,
      keySymptoms: JSON.stringify([
        "Frequent loose stools (>10/day)",
        "Severe dehydration signs",
        "Lethargy or altered consciousness",
        "Sunken eyes",
        "Weak or absent pulse",
        "Cold extremities",
      ]),
      redFlags: JSON.stringify([
        "Signs of hypovolemic shock",
        "Severe malnutrition",
        "Blood in stool",
        "Severe abdominal pain",
        "Inability to drink",
      ]),
      diagnosticCriteria: JSON.stringify({
        dehydration: "Sunken eyes, skin turgor >2 seconds, weak pulse",
        shock: "Weak pulse, cold extremities, altered mental status",
        electrolytes: "Check K+, Na+, Cl-",
      }),
      initialAssessment:
        "Assess dehydration severity (mild, moderate, severe). Check for shock signs. Establish IV access if severe.",
    },
    steps: [
      {
        stepNumber: 1,
        title: "Initial Assessment",
        description: "Assess the degree of dehydration and signs of shock",
        action:
          "Check skin turgor, eyes, mucous membranes, urine output, mental status, pulse quality",
        expectedOutcome: "Classification of dehydration severity",
        timeframe: "Immediately",
        vitalSignThreshold: JSON.stringify({
          heartRate: "> 120 bpm indicates severe dehydration",
          bloodPressure: "Systolic < 90 mmHg indicates shock",
        }),
        medications: JSON.stringify([]),
        investigations: JSON.stringify(["Blood glucose", "Electrolytes", "Blood culture if febrile"]),
        warnings: JSON.stringify(["Do not delay IV fluids for severe dehydration"]),
      },
      {
        stepNumber: 2,
        title: "Establish IV Access",
        description: "Secure IV access for fluid resuscitation",
        action:
          "Establish peripheral IV (18-20G). If unsuccessful, consider IO access. Prepare fluids.",
        expectedOutcome: "Successful IV access established",
        timeframe: "Within 5 minutes",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify(["Avoid central lines in hypovolemic shock initially"]),
      },
      {
        stepNumber: 3,
        title: "Fluid Resuscitation",
        description: "Rapid IV fluid replacement for shock",
        action:
          "Give 20 mL/kg 0.9% saline or Ringer's lactate IV bolus over 30 minutes. Reassess after each bolus.",
        expectedOutcome: "Improved perfusion, stronger pulse, improved mental status",
        timeframe: "30 minutes",
        vitalSignThreshold: JSON.stringify({
          pulse: "Should improve and become stronger",
          capillaryRefill: "Should be < 2 seconds",
        }),
        medications: JSON.stringify(["0.9% Saline or Ringer's lactate"]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify([
          "Monitor for signs of fluid overload",
          "Reassess after each bolus",
        ]),
      },
      {
        stepNumber: 4,
        title: "Maintenance and Replacement",
        description: "Continue fluid therapy and replace ongoing losses",
        action:
          "Maintenance: 50 mL/kg/day for first 20 kg + 20 mL/kg for each kg > 20. Add 10 mL/kg for each diarrheal stool.",
        expectedOutcome: "Adequate hydration maintained, urine output > 1 mL/kg/hour",
        timeframe: "Ongoing",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify(["0.9% Saline with 20 mEq/L KCl"]),
        investigations: JSON.stringify(["Electrolytes at 4-6 hours"]),
        warnings: JSON.stringify(["Add KCl only after urine output confirmed"]),
      },
      {
        stepNumber: 5,
        title: "Oral Rehydration",
        description: "Transition to oral rehydration when tolerated",
        action:
          "Once stable, offer ORS (WHO formula). Small frequent amounts. Continue breastfeeding if applicable.",
        expectedOutcome: "Child tolerating oral fluids, maintaining hydration",
        timeframe: "When stable",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify(["ORS solution"]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify(["Do not use hypotonic fluids", "Avoid milk initially"]),
      },
      {
        stepNumber: 6,
        title: "Nutritional Support",
        description: "Resume feeding as soon as possible",
        action:
          "Offer age-appropriate foods. Continue breastfeeding. Avoid high-fat, high-fiber foods initially.",
        expectedOutcome: "Child tolerating regular diet",
        timeframe: "Within 4-6 hours of stabilization",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify(["Early feeding reduces complications"]),
      },
    ],
  },

  pneumonia: {
    protocol: {
      name: "Severe Pneumonia",
      category: "pneumonia",
      description: "Management of severe community-acquired pneumonia in children",
      ageMin: 0,
      ageMax: 216,
      severity: "severe",
      estimatedMortality: 5.0,
      keySymptoms: JSON.stringify([
        "Cough for > 14 days",
        "Fast breathing (RR > 50 in <5 years, > 40 in >5 years)",
        "Chest indrawing",
        "Stridor at rest",
        "Severe malnutrition",
      ]),
      redFlags: JSON.stringify([
        "Inability to drink",
        "Persistent vomiting",
        "Lethargy or unconsciousness",
        "Severe respiratory distress",
        "Cyanosis",
      ]),
      diagnosticCriteria: JSON.stringify({
        clinical: "Cough + fast breathing + chest indrawing",
        xray: "Consolidation or infiltrates",
        hypoxemia: "SpO2 < 90% on room air",
      }),
      initialAssessment: "Assess respiratory distress severity. Check oxygen saturation. Auscultate lungs.",
    },
    steps: [
      {
        stepNumber: 1,
        title: "Oxygen Therapy",
        description: "Ensure adequate oxygenation",
        action: "Give oxygen to maintain SpO2 > 90%. Use nasal cannula, mask, or high-flow oxygen.",
        expectedOutcome: "SpO2 > 90%",
        timeframe: "Immediately",
        vitalSignThreshold: JSON.stringify({
          oxygenSaturation: "< 90% requires oxygen",
        }),
        medications: JSON.stringify(["Oxygen"]),
        investigations: JSON.stringify(["Pulse oximetry", "Chest X-ray"]),
        warnings: JSON.stringify(["Do not delay oxygen therapy"]),
      },
      {
        stepNumber: 2,
        title: "Antibiotic Therapy",
        description: "Start empiric antibiotics",
        action:
          "First-line: Amoxicillin 45 mg/kg/dose IV/IM 6-hourly + Gentamicin 7.5 mg/kg/day IV/IM once daily",
        expectedOutcome: "Fever resolution within 48-72 hours",
        timeframe: "Within 1 hour",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([
          "Amoxicillin 45 mg/kg/dose IV/IM 6-hourly",
          "Gentamicin 7.5 mg/kg/day IV/IM once daily",
        ]),
        investigations: JSON.stringify(["Blood culture", "Sputum culture if possible"]),
        warnings: JSON.stringify([
          "Check renal function before gentamicin",
          "Adjust for severe malnutrition",
        ]),
      },
      {
        stepNumber: 3,
        title: "Supportive Care",
        description: "Provide supportive measures",
        action: "IV fluids, maintain nutrition, monitor vital signs hourly",
        expectedOutcome: "Stable vital signs, maintained hydration",
        timeframe: "Ongoing",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify(["Avoid fluid overload"]),
      },
      {
        stepNumber: 4,
        title: "Reassessment",
        description: "Assess response to treatment",
        action: "At 48 hours: check fever, respiratory rate, oxygen requirement",
        expectedOutcome: "Improvement in respiratory distress",
        timeframe: "48 hours",
        vitalSignThreshold: JSON.stringify({
          respiratoryRate: "Should decrease",
          fever: "Should resolve",
        }),
        medications: JSON.stringify([]),
        investigations: JSON.stringify(["Repeat chest X-ray if no improvement"]),
        warnings: JSON.stringify(["Consider complications if no improvement"]),
      },
    ],
  },

  malaria: {
    protocol: {
      name: "Severe Malaria",
      category: "malaria",
      description: "Management of severe malaria in children",
      ageMin: 0,
      ageMax: 216,
      severity: "critical",
      estimatedMortality: 15.0,
      keySymptoms: JSON.stringify([
        "Fever",
        "Altered consciousness",
        "Severe anemia",
        "Acute kidney injury",
        "Pulmonary edema",
        "Hypoglycemia",
      ]),
      redFlags: JSON.stringify([
        "Cerebral malaria (impaired consciousness)",
        "Severe anemia (Hb < 5 g/dL)",
        "Acute kidney injury",
        "Pulmonary edema",
        "Hypoglycemia < 40 mg/dL",
      ]),
      diagnosticCriteria: JSON.stringify({
        parasites: "Malaria parasites on blood smear or RDT positive",
        severity: "Any organ dysfunction",
      }),
      initialAssessment: "Rapid diagnosis with RDT or blood smear. Assess for complications.",
    },
    steps: [
      {
        stepNumber: 1,
        title: "Rapid Diagnosis",
        description: "Confirm malaria diagnosis",
        action: "Perform malaria RDT or blood smear. Do not delay treatment while awaiting results.",
        expectedOutcome: "Malaria confirmed",
        timeframe: "Immediately",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify(["Malaria RDT", "Blood smear"]),
        warnings: JSON.stringify(["Start treatment immediately if clinical suspicion high"]),
      },
      {
        stepNumber: 2,
        title: "Parenteral Artemisinin",
        description: "Start IV/IM artemisinin",
        action:
          "Artesunate 3.2 mg/kg IV/IM at 0, 24, 48 hours, then daily. Or artemether if artesunate unavailable.",
        expectedOutcome: "Parasitemia clearance",
        timeframe: "Immediately",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify(["Artesunate 3.2 mg/kg IV/IM"]),
        investigations: JSON.stringify(["Parasitemia level"]),
        warnings: JSON.stringify(["Artesunate superior to artemether"]),
      },
      {
        stepNumber: 3,
        title: "Manage Complications",
        description: "Address organ dysfunction",
        action:
          "Cerebral malaria: Manage seizures, maintain airway. Severe anemia: Transfuse if Hb < 5 or symptoms. AKI: Monitor urine output, manage fluids.",
        expectedOutcome: "Complications controlled",
        timeframe: "Ongoing",
        vitalSignThreshold: JSON.stringify({
          hemoglobin: "< 5 g/dL requires transfusion",
          urine: "< 0.5 mL/kg/hour indicates AKI",
        }),
        medications: JSON.stringify(["Blood for transfusion", "Diuretics if pulmonary edema"]),
        investigations: JSON.stringify(["Hemoglobin", "Creatinine", "Urine output"]),
        warnings: JSON.stringify(["Transfuse slowly to avoid pulmonary edema"]),
      },
      {
        stepNumber: 4,
        title: "Follow-up Treatment",
        description: "Complete treatment with oral antimalarials",
        action:
          "After 3 doses of parenteral artemisinin, switch to artemisinin-based combination therapy (ACT) orally for 3 days total.",
        expectedOutcome: "Parasite clearance, clinical recovery",
        timeframe: "After 3 parenteral doses",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify(["Artemisinin-based combination therapy"]),
        investigations: JSON.stringify(["Blood smear at day 7"]),
        warnings: JSON.stringify(["Complete full course of ACT"]),
      },
    ],
  },

  meningitis: {
    protocol: {
      name: "Bacterial Meningitis",
      category: "meningitis",
      description: "Management of suspected bacterial meningitis in children",
      ageMin: 0,
      ageMax: 216,
      severity: "critical",
      estimatedMortality: 10.0,
      keySymptoms: JSON.stringify([
        "Fever",
        "Neck stiffness",
        "Headache",
        "Altered consciousness",
        "Petechial/purpuric rash",
        "Seizures",
      ]),
      redFlags: JSON.stringify([
        "Petechial or purpuric rash",
        "Altered consciousness",
        "Seizures",
        "Signs of shock",
        "Inability to drink",
      ]),
      diagnosticCriteria: JSON.stringify({
        clinical: "Fever + neck stiffness + headache",
        csf: "Elevated WBC, elevated protein, low glucose",
        culture: "Positive CSF or blood culture",
      }),
      initialAssessment: "High suspicion warrants immediate antibiotics. Do not delay for LP.",
    },
    steps: [
      {
        stepNumber: 1,
        title: "Immediate Antibiotics",
        description: "Start empiric antibiotics immediately",
        action:
          "Ceftriaxone 80 mg/kg/day IV/IM divided in 2 doses (max 4g/day) + Vancomycin 15-20 mg/kg/dose IV 4-6 hourly",
        expectedOutcome: "Bacterial eradication",
        timeframe: "Within 30 minutes",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([
          "Ceftriaxone 80 mg/kg/day IV/IM",
          "Vancomycin 15-20 mg/kg/dose IV 4-6 hourly",
        ]),
        investigations: JSON.stringify(["Blood culture before antibiotics if possible"]),
        warnings: JSON.stringify(["Do not delay antibiotics for LP or imaging"]),
      },
      {
        stepNumber: 2,
        title: "Dexamethasone",
        description: "Give corticosteroids to reduce inflammation",
        action: "Dexamethasone 0.15 mg/kg/dose IV 6-hourly for 4 days. Give before or with first antibiotic.",
        expectedOutcome: "Reduced neurological complications",
        timeframe: "With first antibiotic",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify(["Dexamethasone 0.15 mg/kg/dose IV 6-hourly"]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify(["Most effective if given before antibiotics"]),
      },
      {
        stepNumber: 3,
        title: "Supportive Care",
        description: "Manage complications and maintain homeostasis",
        action:
          "IV fluids (restrict to 2/3 maintenance due to SIADH), manage seizures, maintain airway, monitor ICP",
        expectedOutcome: "Stable vital signs, seizures controlled",
        timeframe: "Ongoing",
        vitalSignThreshold: JSON.stringify({
          sodium: "Monitor for hyponatremia",
          seizures: "Treat immediately",
        }),
        medications: JSON.stringify(["Anticonvulsants if seizures"]),
        investigations: JSON.stringify(["Serum sodium", "CSF analysis if LP done"]),
        warnings: JSON.stringify(["Restrict fluids to avoid cerebral edema"]),
      },
      {
        stepNumber: 4,
        title: "Lumbar Puncture",
        description: "Obtain CSF for diagnosis and culture",
        action:
          "Perform LP when stable. Send CSF for cell count, glucose, protein, culture, Gram stain.",
        expectedOutcome: "Confirmed bacterial meningitis",
        timeframe: "After stabilization",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify(["CSF culture", "CSF Gram stain", "CSF glucose/protein"]),
        warnings: JSON.stringify(["Do not delay antibiotics for LP"]),
      },
    ],
  },

  shock: {
    protocol: {
      name: "Pediatric Septic Shock",
      category: "shock",
      description: "Management of septic shock in children",
      ageMin: 0,
      ageMax: 216,
      severity: "critical",
      estimatedMortality: 20.0,
      keySymptoms: JSON.stringify([
        "Fever or hypothermia",
        "Tachycardia",
        "Tachypnea",
        "Weak or absent pulses",
        "Cold extremities",
        "Altered mental status",
      ]),
      redFlags: JSON.stringify([
        "Hypotension",
        "Altered consciousness",
        "Mottled skin",
        "Weak pulses",
        "Metabolic acidosis",
      ]),
      diagnosticCriteria: JSON.stringify({
        clinical: "Signs of infection + signs of hypoperfusion",
        labs: "Elevated lactate, metabolic acidosis",
      }),
      initialAssessment: "Assess perfusion: pulse quality, skin temperature, mental status, urine output.",
    },
    steps: [
      {
        stepNumber: 1,
        title: "Establish IV Access",
        description: "Secure IV or IO access immediately",
        action: "Establish peripheral IV (18-20G). If unsuccessful, use IO access. Prepare fluids.",
        expectedOutcome: "Successful vascular access",
        timeframe: "Within 5 minutes",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify([]),
        warnings: JSON.stringify(["Do not delay fluid resuscitation for perfect IV"]),
      },
      {
        stepNumber: 2,
        title: "Rapid Fluid Resuscitation",
        description: "Give rapid IV fluid bolus",
        action:
          "20 mL/kg 0.9% saline or Ringer's lactate IV over 15-30 minutes. Repeat if signs of shock persist.",
        expectedOutcome: "Improved perfusion, stronger pulses, improved mental status",
        timeframe: "15-30 minutes",
        vitalSignThreshold: JSON.stringify({
          pulse: "Should improve",
          capillaryRefill: "Should be < 2 seconds",
          urine: "Should be > 1 mL/kg/hour",
        }),
        medications: JSON.stringify(["0.9% Saline or Ringer's lactate"]),
        investigations: JSON.stringify(["Lactate level", "Blood culture"]),
        warnings: JSON.stringify(["Reassess after each bolus", "Up to 60 mL/kg may be needed"]),
      },
      {
        stepNumber: 3,
        title: "Antibiotics",
        description: "Start broad-spectrum antibiotics",
        action:
          "Ceftriaxone 80 mg/kg/day IV/IM + Gentamicin 7.5 mg/kg/day IV/IM once daily (or Vancomycin if resistant suspected)",
        expectedOutcome: "Infection controlled",
        timeframe: "Within 1 hour",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([
          "Ceftriaxone 80 mg/kg/day IV/IM",
          "Gentamicin 7.5 mg/kg/day IV/IM",
        ]),
        investigations: JSON.stringify(["Blood culture", "Lactate", "Procalcitonin"]),
        warnings: JSON.stringify(["Obtain cultures before antibiotics if possible"]),
      },
      {
        stepNumber: 4,
        title: "Vasopressor Support",
        description: "Start vasopressors if hypotensive after fluids",
        action:
          "If SBP < 5th percentile after fluids: Epinephrine 0.05-0.3 mcg/kg/min IV infusion. Titrate to effect.",
        expectedOutcome: "Improved blood pressure and perfusion",
        timeframe: "After fluid boluses",
        vitalSignThreshold: JSON.stringify({
          bloodPressure: "Target SBP > 5th percentile for age",
        }),
        medications: JSON.stringify(["Epinephrine 0.05-0.3 mcg/kg/min IV infusion"]),
        investigations: JSON.stringify(["Continuous cardiac monitoring"]),
        warnings: JSON.stringify(["Requires ICU monitoring", "Central line preferred for infusion"]),
      },
      {
        stepNumber: 5,
        title: "Source Control",
        description: "Identify and treat source of infection",
        action:
          "Imaging as needed (CXR, abdominal imaging). Surgical intervention if abscess or perforation.",
        expectedOutcome: "Source identified and treated",
        timeframe: "After stabilization",
        vitalSignThreshold: JSON.stringify({}),
        medications: JSON.stringify([]),
        investigations: JSON.stringify(["Imaging studies"]),
        warnings: JSON.stringify(["Do not delay antibiotics for imaging"]),
      },
    ],
  },
};
