import test from "node:test";
import assert from "node:assert/strict";
import { firstAvailableName, REQUIRED_COLUMNS, REQUIRED_TABLES } from "./verify-iers-readiness.mjs";

test("IERS verifier accepts the deployed mixed table naming contract", () => {
  const deployedTables = new Set([
    "institutionMemberships",
    "iersActivationEvents",
    "iersActivationResponders",
    "iersActivationTimeline",
    "iers_evidence_records",
    "iers_action_items",
    "iers_drills",
    "iers_drill_participants",
    "iers_implementation_milestones",
    "iersCompetencyRecords",
    "trainingSchedules",
    "institutionalProducts",
    "institutionalProductCapabilities",
    "institutionalProductPlans",
    "institutionProductSubscriptions",
    "institutionProductEntitlements",
    "institutionProductRoles",
    "institutionAccountScopes",
    "institutionAccountScopeEvents",
    "institutionSubscriptionEvents",
    "institutionEntitlementAuditLog",
    "institutionDataLifecyclePolicies",
    "institutionDataLifecycleRequests",
    "institutionSubscriptionPayments",
    "institutionSubscriptionPaymentIntents",
    "institutionRenewalNotificationPreferences",
    "institutionRenewalNotifications",
    "institutionConnectedServices",
    "institutionConnectedServiceEvents",
    "safeTruthGovernancePolicies",
    "safeTruthGovernancePolicyEvents",
    "facility_poles",
    "facility_departments",
    "ertl_weekly_rotations",
    "shift_utl_rosters",
    "institution_department_response_coordinators",
    "institution_department_response_coordinator_events",
  ]);

  for (const requirement of REQUIRED_TABLES) {
    assert.ok(
      firstAvailableName(deployedTables, requirement.names),
      `expected a deployed table alias for ${requirement.label}`,
    );
  }
});

test("IERS verifier accepts camelCase columns for the first two migration groups", () => {
  const deployedColumns = new Set([
    "responsibilityRole",
    "membershipStatus",
    "status",
    "triggeredAt",
    "notificationStatus",
    "eventType",
    "criterion_code",
    "reviewed_by_user_id",
    "owner_user_id",
    "closure_evidence_id",
    "legacy_action_log_id",
    "debrief_note",
    "is_simulation",
    "simulation_label",
    "no_patient_identifiers_acknowledged",
    "evidence_id",
    "programType",
    "competencyStatus",
    "trainingAttendanceId",
    "endDate",
    "productKey",
    "capabilityKey",
    "planKey",
    "subscriptionStatus",
    "entitlementStatus",
    "roleStatus",
    "roleKey",
    "invitedEmail",
    "scopeKey",
    "scopeStatus",
    "eventType",
    "decision",
    "retentionDays",
    "legalHold",
    "requestType",
    "reason",
    "paymentReference",
    "idempotencyKey",
    "checkoutRequestId",
    "status",
    "mpesaReceiptNumber",
    "inAppEnabled",
    "reminderDays",
    "dedupeKey",
    "channel",
    "serviceKey",
    "lifecycleStatus",
    "privacyClass",
    "owner",
    "boundaryStatus",
    "allowedRoute",
    "patientIdentifiersAllowed",
    "providerLinkageAllowed",
    "institution_id",
    "pole_id",
    "department_id",
    "ertl_user_id",
    "assignment_status",
    "accepted_at",
    "utl_user_id",
    "coordinator_user_id",
    "effective_from",
    "event_type",
    "actor_user_id",
  ]);

  for (const requirement of REQUIRED_COLUMNS) {
    assert.ok(
      firstAvailableName(deployedColumns, requirement.names),
      `expected a deployed column alias for ${requirement.label}`,
    );
  }
});
