import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { PassThrough } from "node:stream";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

export type ProfessionalProgressPdfData = {
  reportId: number;
  verificationCode: string;
  verificationUrl: string;
  snapshotHash: string;
  generatedAt: Date | string;
  reportStatus?: "active" | "revoked" | "superseded";
  publicExpiresAt?: Date | string | null;
  supersededByReportId?: number | null;
  subject: { name?: string | null; email?: string | null; cadre?: string | null };
  period: { type: string; start: string; end: string };
  reportScope: string;
  lifeSupport?: Array<{ program: string; source?: string; phase?: string; percentage?: number; status?: string; recordStatus?: string; evidenceStrength?: string; verificationMethod?: string | null; expiresAt?: string | Date | null }>;
  externalCompletions?: Array<{ program: string; source?: string; phase?: string; percentage?: number; status?: string; evidenceStrength?: string; verificationMethod?: string | null }>;
  pathways?: Array<{ program: string; source?: string; phase?: string; percentage?: number; status?: string; paymentStatus?: string | null }>;
  coursework?: Array<{ title: string; category?: string; percentage?: number; status?: string; completedAt?: string | Date | null; evidenceStrength?: string }>;
  cpd?: { verifiedSessions?: number; sessionsAttended?: number; sessionsPresented?: number | null; points?: number; sessions?: Array<{ title: string; date?: string | Date | null; points?: number }> };
  qualityReports?: { careSignalSubmitted?: number | null; codeSignalSubmitted?: number | null; metricsStatus?: "complete" | "partial" };
  fellowship?: { overallPercentage?: number; coursesPercentage?: number; resusGPSPercentage?: number; careSignalPercentage?: number } | null;
  goals?: Array<{ title: string; metricKey?: string; targetValue: number | string; actualValue?: number | string; progressValue?: number | string; computedStatus?: string; unit?: string; periodType?: string; periodStart?: string | Date; periodEnd?: string | Date }>;
  certificates?: Array<{ programType?: string; certificateNumber?: string | null; issueDate?: string | Date | null; expiryDate?: string | Date | null; verificationCode?: string | null; verificationStatus?: string; source?: string }>;
  competenceEvidence?: Array<{ competencyDomain: string; assessmentType: string; assessmentDate: string | Date; assessmentMethod: string; result: string; validUntil?: string | Date | null; evidenceReference?: string | null; status?: string; effectiveStatus?: string }>;
  evidence?: Array<{ title: string; evidenceType: string; status: string; evidenceStrength: string; sourceSystem: string; verificationMethod?: string | null; expiresAt?: string | Date | null }>;
  periodSemantics?: string;
};

const COLORS = { navy: "#0B2447", teal: "#0F766E", cyan: "#1FB6C1", orange: "#E56B2F", ink: "#172033", muted: "#5B6577", line: "#D8E1EA", pale: "#F3F7FA", white: "#FFFFFF", red: "#B42318" };
const APP_BASE = (process.env.APP_BASE_URL?.trim() || "https://www.paedsresus.com").replace(/\/$/, "");
function text(value: unknown, fallback = "—"): string { if (value == null || String(value).trim() === "") return fallback; return String(value); }
function dateLabel(value: unknown): string { if (!value) return "—"; const date = value instanceof Date ? value : new Date(String(value)); if (Number.isNaN(date.getTime())) return String(value).slice(0, 10); return date.toLocaleDateString("en-KE", { year: "numeric", month: "short", day: "numeric", timeZone: "Africa/Nairobi" }); }
function slug(value: string): string { return value.normalize("NFKD").replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "-").replace(/-+/g, "-").slice(0, 60) || "provider"; }
function titleCase(value: unknown): string { return text(value).replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()); }
function learningLabel(percentage: unknown): string { return `${Math.max(0, Math.min(100, Number(percentage) || 0))}% of required learning activities`; }
function statusLabel(value: unknown): string { return titleCase(value); }
export function competenceValidityLabel(item: { result: string; effectiveStatus?: string; status?: string; assessmentMethod: string; assessmentDate: string | Date; validUntil?: string | Date | null }): string {
  return `Result: ${titleCase(item.result)} · Current validity: ${titleCase(item.effectiveStatus ?? item.status ?? item.result)} · ${titleCase(item.assessmentMethod)} · assessed ${dateLabel(item.assessmentDate)} · valid ${item.validUntil ? `until ${dateLabel(item.validUntil)}` : "not specified"}`;
}

export function professionalProgressPdfFilename(data: Pick<ProfessionalProgressPdfData, "subject" | "reportId">): string { return `Paeds-Resus-Professional-Progress-${slug(text(data.subject.name, "Provider"))}-${data.reportId}.pdf`; }
function drawFooter(doc: PDFKit.PDFDocument, data: ProfessionalProgressPdfData, pageNumber: number) { const y = doc.page.height - 35; const bottom = doc.page.margins.bottom; const ox = doc.x; const oy = doc.y; doc.page.margins.bottom = 0; doc.save(); doc.strokeColor(COLORS.line).lineWidth(0.6).moveTo(42, y - 8).lineTo(doc.page.width - 42, y - 8).stroke(); doc.font("Helvetica").fontSize(7).fillColor(COLORS.muted); doc.text(`Paeds Resus · ${data.verificationUrl}`, 42, y, { width: doc.page.width - 180, lineBreak: false }); doc.text(`Report ID ${data.reportId} · Page ${pageNumber}`, doc.page.width - 135, y, { width: 93, align: "right", lineBreak: false }); doc.restore(); doc.page.margins.bottom = bottom; doc.x = ox; doc.y = oy; }
function heading(doc: PDFKit.PDFDocument, title: string, subtitle?: string) { doc.x = 42; doc.moveDown(0.8); doc.font("Helvetica-Bold").fontSize(14).fillColor(COLORS.navy).text(title); if (subtitle) doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted).text(subtitle, { width: doc.page.width - 84 }); doc.moveDown(0.35); }
function row(doc: PDFKit.PDFDocument, label: string, value: string, options: { status?: string } = {}) { const x = 42; const width = doc.page.width - 84; const y = doc.y; const height = 34; doc.roundedRect(x, y, width, height, 4).fillAndStroke(COLORS.pale, COLORS.line); doc.font("Helvetica-Bold").fontSize(8.5).fillColor(COLORS.ink).text(label, x + 10, y + 7, { width: width * 0.32, lineBreak: false }); doc.font("Helvetica").fontSize(8).fillColor(COLORS.muted).text(value, x + width * 0.34, y + 7, { width: width * 0.42, lineBreak: false }); if (options.status) doc.font("Helvetica-Bold").fontSize(7.5).fillColor(COLORS.teal).text(statusLabel(options.status), x + width - 128, y + 8, { width: 118, align: "right", lineBreak: false }); doc.y = y + height + 5; }
function ensureSpace(doc: PDFKit.PDFDocument, needed = 80) { if (doc.y + needed > doc.page.height - 58) doc.addPage(); }
function drawQr(doc: PDFKit.PDFDocument, value: string, x: number, y: number, size: number) { const qr = QRCode.create(value, { errorCorrectionLevel: "M" }); const modules = qr.modules; const cell = size / modules.size; doc.save(); doc.rect(x, y, size, size).fill(COLORS.white); doc.fillColor(COLORS.ink); for (let rowIndex = 0; rowIndex < modules.size; rowIndex += 1) for (let col = 0; col < modules.size; col += 1) if (modules.data[rowIndex * modules.size + col]) doc.rect(x + col * cell, y + rowIndex * cell, cell + 0.1, cell + 0.1).fill(); doc.restore(); }
function reportStatusLabel(data: ProfessionalProgressPdfData): string { if (data.reportStatus === "revoked") return "REVOKED — DO NOT RELY ON THIS DOCUMENT"; if (data.reportStatus === "superseded") return `SUPERSEDED${data.supersededByReportId ? ` — SEE REPORT ${data.supersededByReportId}` : ""}`; return "ACTIVE"; }
function goalMetricLabel(metricKey: unknown): string { const labels: Record<string, string> = { cpd_points: "CPD points", cpd_sessions: "CPD sessions attended", cpd_sessions_attended: "CPD sessions attended", cpd_sessions_presented: "CPD sessions presented", life_support_completed: "Life-support courses completed", life_support_courses_completed: "Life-support courses completed", fellowship_completion: "Paeds Resus Fellowship" }; return labels[String(metricKey)] ?? "Professional development"; }
function drawMetricCard(doc: PDFKit.PDFDocument, x: number, y: number, width: number, title: string, value: string, detail: string, colour: string) { const height = 58; doc.roundedRect(x, y, width, height, 5).fillAndStroke(COLORS.pale, COLORS.line); doc.rect(x, y, 5, height).fill(colour); doc.font("Helvetica-Bold").fontSize(7.5).fillColor(COLORS.muted).text(title.toUpperCase(), x + 14, y + 9, { width: width - 22, lineBreak: false }); doc.font("Helvetica-Bold").fontSize(17).fillColor(COLORS.navy).text(value, x + 14, y + 21, { width: width - 22, lineBreak: false }); doc.font("Helvetica").fontSize(7.5).fillColor(COLORS.muted).text(detail, x + 14, y + 42, { width: width - 22, lineBreak: false }); }
function drawGoalBar(doc: PDFKit.PDFDocument, goal: NonNullable<ProfessionalProgressPdfData["goals"]>[number], x: number, y: number, width: number) { const progress = Math.max(0, Math.min(100, Number(goal.progressValue ?? 0))); const status = String(goal.computedStatus ?? "active"); doc.font("Helvetica-Bold").fontSize(8).fillColor(COLORS.ink).text(`${text(goal.title)} · ${goalMetricLabel(goal.metricKey)}`, x, y, { width: width - 80, lineBreak: false }); doc.font("Helvetica-Bold").fontSize(8).fillColor(status === "achieved" ? COLORS.teal : status === "at_risk" || status === "expired" ? COLORS.red : COLORS.navy).text(`${progress}%`, x + width - 42, y, { width: 42, align: "right", lineBreak: false }); doc.roundedRect(x, y + 13, width, 7, 3).fill("#E5EDF2"); if (progress > 0) doc.roundedRect(x, y + 13, width * progress / 100, 7, 3).fill(status === "achieved" ? COLORS.teal : status === "at_risk" || status === "expired" ? COLORS.orange : COLORS.cyan); doc.font("Helvetica").fontSize(7).fillColor(COLORS.muted).text(`${Number(goal.actualValue ?? 0)} of ${Number(goal.targetValue)} ${text(goal.unit, "units")} · ${text(goal.periodType)}${goal.periodEnd ? ` ends ${dateLabel(goal.periodEnd)}` : ""}`, x, y + 25, { width, lineBreak: false }); }

export function generateProfessionalProgressPdf(data: ProfessionalProgressPdfData): PassThrough {
  const doc = new PDFDocument({ size: "A4", margins: { top: 42, bottom: 58, left: 42, right: 42 }, info: { Title: "Paeds Resus Professional Progress Report", Author: "Paeds Resus", Subject: `Report ${data.reportId}`, Keywords: `Paeds Resus, professional learning, ${data.verificationCode}` } });
  const stream = new PassThrough(); doc.pipe(stream); let pageNumber = 1; doc.on("pageAdded", () => { pageNumber += 1; drawFooter(doc, data, pageNumber); });
  doc.rect(0, 0, doc.page.width, doc.page.height).fill(COLORS.white); const logoPath = resolve(process.cwd(), "client/public/paeds-resus-logo-brand.png"); if (existsSync(logoPath)) { try { doc.image(logoPath, 42, 34, { fit: [150, 42] }); } catch { /* text branding remains available */ } }
  doc.fillColor(COLORS.teal).rect(42, 86, doc.page.width - 84, 4).fill(); doc.font("Helvetica-Bold").fontSize(22).fillColor(COLORS.navy).text("Professional Progress Report", 42, 108); doc.font("Helvetica").fontSize(9).fillColor(COLORS.muted).text("Professional learning and evidence record", 42, 136); doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.ink).text(text(data.subject.name, "Provider"), 42, 164); doc.font("Helvetica").fontSize(9).fillColor(COLORS.muted).text(`${text(data.subject.cadre, "Healthcare provider")} · ${data.period.type} report · ${data.period.start} to ${data.period.end}`, 42, 179);
  const metaY = 208; doc.roundedRect(42, metaY, doc.page.width - 84, 70, 5).fillAndStroke("#EEF7F6", COLORS.line); doc.font("Helvetica-Bold").fontSize(8).fillColor(data.reportStatus === "active" || !data.reportStatus ? COLORS.teal : COLORS.red).text(reportStatusLabel(data), 54, metaY + 11); doc.font("Helvetica").fontSize(8).fillColor(COLORS.ink).text(`Report ID: ${data.reportId}   ·   Issued: ${dateLabel(data.generatedAt)}`, 54, metaY + 27); doc.font("Helvetica").fontSize(7.5).fillColor(COLORS.muted).text(`Public validity: ${data.publicExpiresAt ? `until ${dateLabel(data.publicExpiresAt)}` : "not specified"}`, 54, metaY + 41); doc.font("Helvetica").fontSize(7.5).fillColor(COLORS.muted).text(`Verify: ${data.verificationUrl}`, 54, metaY + 54, { width: doc.page.width - 108, lineBreak: false }); doc.y = metaY + 92;
  ensureSpace(doc, 240); heading(doc, "At a glance", "A plain-language view of what you did, what you completed, and what you are working towards during this report period."); const cardWidth = (doc.page.width - 96) / 2; const glanceY = doc.y; const attended = data.cpd?.sessionsAttended ?? data.cpd?.verifiedSessions ?? 0; const presented = data.cpd?.sessionsPresented; const completedCourses = (data.lifeSupport ?? []).filter(item => item.status === "completed" || item.percentage === 100).length; const totalCourses = (data.lifeSupport ?? []).length; const fellowshipPct = data.fellowship?.overallPercentage; const care = data.qualityReports?.careSignalSubmitted; const code = data.qualityReports?.codeSignalSubmitted; drawMetricCard(doc, 42, glanceY, cardWidth, "CPD attended", String(attended), `${Number(data.cpd?.points ?? 0).toFixed(1)} points verified`, COLORS.teal); drawMetricCard(doc, 54 + cardWidth, glanceY, cardWidth, "CPD presented", presented == null ? "—" : String(presented), presented == null ? "Supplementary source unavailable" : "Lead or co-presenter sessions", COLORS.cyan); drawMetricCard(doc, 42, glanceY + 68, cardWidth, "Life support", `${completedCourses}/${totalCourses}`, totalCourses ? "courses completed / linked" : "No linked course records", COLORS.orange); drawMetricCard(doc, 54 + cardWidth, glanceY + 68, cardWidth, "Fellowship", fellowshipPct == null ? "—" : `${Math.round(Number(fellowshipPct))}%`, fellowshipPct == null ? "No Fellowship record linked" : "Paeds Resus Fellowship learning", COLORS.navy); doc.y = glanceY + 136; if (care != null || code != null) { doc.font("Helvetica").fontSize(8).fillColor(COLORS.muted).text(`Quality improvement reports submitted · Care Signal: ${care ?? "—"} · Code Signal: ${code ?? "—"}`, 42, doc.y, { width: doc.page.width - 84, lineBreak: false }); doc.y += 16; }
  const goals = (data.goals ?? []).filter(goal => goal.computedStatus !== "expired").slice(0, 4); if (goals.length) { heading(doc, "Your goals", "Targets are linked to measurable platform records. Progress is calculated from the same evidence used in this report."); goals.forEach(goal => { drawGoalBar(doc, goal, 42, doc.y, doc.page.width - 84); doc.y += 48; }); }
  heading(doc, "What this report establishes"); doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.ink).text("This report records professional learning, credentials, verified attendance, assessments, and other evidence available in the Paeds Resus platform at the time of generation.", { width: doc.page.width - 84, lineGap: 3 }); doc.moveDown(0.45); doc.font("Helvetica-Bold").fontSize(8.5).fillColor(COLORS.ink).text("What it does not establish"); doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted).text("Learning completion does not by itself establish independent clinical competence. Statutory licensure, employer credentialing, and scope of practice remain governed by the relevant authority or employer.", { width: doc.page.width - 84, lineGap: 3 });
  ensureSpace(doc, 125); heading(doc, "Verify this report"); const qrY = doc.y; drawQr(doc, data.verificationUrl, 42, qrY, 88); doc.font("Helvetica-Bold").fontSize(9).fillColor(COLORS.teal).text("Scan to verify online", 145, qrY + 10); doc.font("Helvetica").fontSize(8).fillColor(COLORS.muted).text(`Verification code: ${data.verificationCode}`, 145, qrY + 29); doc.font("Helvetica").fontSize(7.5).fillColor(COLORS.muted).text("The QR code and verification URL are the primary human verification methods. The SHA-256 value below is the cryptographic integrity layer.", 145, qrY + 48, { width: doc.page.width - 190, lineGap: 3 }); doc.y = qrY + 104;
  heading(doc, "Evidence summary", "Evidence strength is shown explicitly; no aggregate life-support readiness score is used."); const evidence = data.evidence ?? []; row(doc, "Credentials", `${evidence.filter(item => item.evidenceType === "credential").length} recorded`, { status: "credential" }); row(doc, "Learning records", `${evidence.filter(item => item.evidenceType === "learning").length} recorded`, { status: "learning" }); row(doc, "Verified attendance", `${evidence.filter(item => item.evidenceType === "cpd").length} record(s)`, { status: "verified_attendance" }); row(doc, "Observed competence", `${(data.competenceEvidence ?? []).filter(item => item.status !== "expired").length} assessment(s)`, { status: "assessed" });
  ensureSpace(doc, 100); heading(doc, data.reportScope === "activity" ? "Life-support current status — context only" : "Life-support credentials and learning", "Each programme is listed separately. A learning percentage describes required learning activities; it is not a competence or readiness score."); const ls = data.lifeSupport ?? []; if (ls.length) ls.forEach(item => { const progress = item.evidenceStrength === "credential" ? "Credential record" : learningLabel(item.percentage); const expiry = item.expiresAt ? ` · valid until ${dateLabel(item.expiresAt)}` : ""; row(doc, text(item.program), `${progress} · ${text(item.source)}${expiry}`, { status: item.evidenceStrength ?? item.recordStatus ?? item.status }); }); else doc.font("Helvetica").fontSize(9).fillColor(COLORS.muted).text("No life-support course record is linked to this snapshot.");
  const external = data.externalCompletions ?? []; if (external.length) { ensureSpace(doc, 100); heading(doc, "External evidence — source verified", "These records were completed outside the Paeds Resus pathway and are visibly separated from Paeds Resus-issued credentials. No course-progress percentage is used for this claim."); external.forEach(item => row(doc, text(item.program), `${statusLabel(item.status ?? "verified_external")} · ${text(item.source)} · ${text(item.phase)}`, { status: "verified_external" })); }
  ensureSpace(doc, 100); heading(doc, data.reportScope === "activity" ? "Programme pathway status — context only" : "Programme pathways", "NERP and IERP pathway status is separate from individual course credentials."); const pathways = data.pathways ?? []; if (pathways.length) pathways.forEach(item => row(doc, text(item.program), `${text(item.phase)} · ${text(item.source)}`, { status: item.status })); else doc.font("Helvetica").fontSize(9).fillColor(COLORS.muted).text("No NERP or IERP pathway is linked to this snapshot.");
  const competence = data.competenceEvidence ?? []; if (competence.length) { ensureSpace(doc, 120); heading(doc, "Observed competence assessments", "Only authorised assessment records are shown here; competence is never inferred from course completion. Current validity is calculated at report generation."); competence.forEach(item => row(doc, item.competencyDomain, competenceValidityLabel(item), { status: item.effectiveStatus ?? item.status ?? item.result })); }
  ensureSpace(doc, 155); heading(doc, "CPD and professional reporting", "Counts are limited to records attributed to this account and included in the signed report scope."); row(doc, "CPD attended", `${data.cpd?.sessionsAttended ?? data.cpd?.verifiedSessions ?? 0} verified session(s) · ${Number(data.cpd?.points ?? 0).toFixed(1)} points`, { status: "verified_attendance" }); row(doc, "CPD presented", data.cpd?.sessionsPresented == null ? "Unavailable — supplementary source could not be read" : `${data.cpd.sessionsPresented} session(s) as lead or co-presenter`, { status: "presented" }); row(doc, "Care Signal reports submitted", data.qualityReports?.careSignalSubmitted == null ? "Unavailable — supplementary source could not be read" : `${data.qualityReports.careSignalSubmitted} submitted report(s)`, { status: "submitted" }); row(doc, "Code Signal reports submitted", data.qualityReports?.codeSignalSubmitted == null ? "Unavailable — supplementary source could not be read" : `${data.qualityReports.codeSignalSubmitted} submitted report(s)`, { status: "submitted" }); const fellowship = data.fellowship; if (fellowship) row(doc, "Paeds Resus Fellowship", "Learning record; component progress available in the platform", { status: "learning" }); (data.coursework ?? []).slice(0, 12).forEach(item => row(doc, text(item.title), `${text(item.category)} · ${learningLabel(item.percentage)}`, { status: item.evidenceStrength ?? item.status }));
  const certificates = data.certificates ?? []; if (certificates.length) { ensureSpace(doc, 120); heading(doc, "Certificates and validity", "Certificate records are shown with issuer/source, verification status, and validity where available."); certificates.slice(0, 20).forEach(cert => row(doc, text(cert.programType, "Certificate"), `${text(cert.source, "Paeds Resus record")} · ${text(cert.certificateNumber, "Certificate number pending")} · issued ${dateLabel(cert.issueDate)} · valid ${cert.expiryDate ? `until ${dateLabel(cert.expiryDate)}` : "not specified"}`, { status: cert.verificationStatus ?? (cert.verificationCode ? "verified" : "recorded") })); }
  ensureSpace(doc, 90); heading(doc, "Verification and report scope"); doc.font("Helvetica").fontSize(8.5).fillColor(COLORS.muted).text(text(data.periodSemantics), { width: doc.page.width - 84, lineGap: 3 }); doc.moveDown(0.5); doc.font("Helvetica-Bold").fontSize(8).fillColor(COLORS.ink).text("Snapshot SHA-256:"); doc.font("Helvetica").fontSize(7.5).fillColor(COLORS.muted).text(data.snapshotHash, { width: doc.page.width - 84 }); doc.font("Helvetica").fontSize(8).fillColor(COLORS.muted).text("This is a professional learning and evidence record. It is not a statutory licence, a blanket competence declaration, or a substitute for employer appraisal and clinical governance.", { width: doc.page.width - 84, lineGap: 3 }); drawFooter(doc, data, pageNumber); doc.end(); return stream;
}
export const professionalProgressAppBase = APP_BASE;
